```{r}
setwd("~/working_paper/rbci/")
getwd()
```

```{r packages, echo=FALSE, }
library(haven)
library(dplyr)
select <- dplyr::select
library(magrittr)
library(stringr)
library(geosphere)
library(purrr)
library(kableExtra)
library(tidyr)
library(readxl)
library(sf)
library(exactextractr)
library(raster)
library(rgdal)
library(ncdf4)
library(terra)
```

#Levels

```{r}
folder_path <- "data/data_raw/gadm"

files <- list.files(folder_path, full.names = TRUE)

levels <- data.frame(file = files) %>%
  mutate(country = str_extract(file, "(?<=_)[A-Z]{3}(?=_\\d)"),
         level = as.integer(str_extract(file, "(?<=_)[0-9]+(?=\\.shp$)"))) %>%
  arrange(country, desc(level)) %>%
  distinct(country, .keep_all = TRUE)

levels %<>%
  group_by(country) %>%
  summarise(levels_nb = first(level))

print(levels, n=40)

cty_adm1 <- levels%>%
  filter(levels_nb>=1)%>%
  pull(country)

cty_adm2 <- levels%>%
  filter(levels_nb>=2)%>%
  pull(country)

cty_adm3 <- levels%>%
  filter(levels_nb>=3)%>%
  pull(country)

cty_adm4 <- levels%>%
  filter(levels_nb>=4)%>%
  pull(country)
```

##Merge internet

```{r}
gg_stack <- readRDS("data/data_rds/gg_stack.rds")
ggg_stack <- readRDS("data/data_rds/ggg_stack.rds")

int_stack <- gg_stack %>%
  left_join(ggg_stack, by = c("iso", "NAME_1", "NAME_2", "NAME_3", "round"))

saveRDS(int_stack, file="data/data_rds/int_stack.rds")

int_stack <- readRDS("data/data_rds/int_stack.rds")

int_stack%<>%
  mutate(pop_adm1= coalesce(pop_adm1.x, pop_adm1.y))%>%
  mutate(pop_adm2 = coalesce(pop_adm2.x, pop_adm2.y))%>%
  mutate(pop_adm3 = coalesce(pop_adm3.x, pop_adm3.y))

int_stack%<>%
  select(-ends_with(".x"), -ends_with(".y"))

data_final <- readRDS("data/data_rds/data_final.rds")

data_final %<>%
  left_join(int_stack, by = c("iso", "NAME_1", "NAME_2", "NAME_3", "round"))

countries_adm1 <- c("GHA","KEN","MOZ", "MWI","NGA","TZA","UGA","ZMB", "ZWE")

countries_adm2 <- c("BEN", "BFA", "BWA", "CIV", "CMR", "GIN", "LBR", "MLI", "NAM", "NER", "SLE")


data_final%<>%
mutate(gg_region_pot = case_when(
    iso %in% countries_adm1 ~ gg_adm1_pot,
    iso %in%  countries_adm2 ~ gg_adm2_pot, 
    TRUE ~ NA_integer_
  ))%>%
mutate(ggg_region_pot = case_when(
    iso %in% countries_adm1 ~ ggg_adm1_pot,
    iso %in%  countries_adm2 ~ ggg_adm2_pot, 
    TRUE ~ NA_integer_))%>%
  mutate(cvg_region_pot=ifelse(is.na(ggg_region_pot), gg_region_pot, ggg_region_pot))


data_final%<>%
mutate(pop_region = case_when(
    iso %in% countries_adm1 ~ pop_adm1,
    iso %in% countries_adm2 ~ pop_adm2, 
    TRUE ~ NA_integer_
  ))%>%
  mutate(pop_region_log=log(pop_region+1))

data_final%<>%
  group_by(NAME_2) %>%
  mutate(name2_id = cur_group_id()) %>%
  ungroup() %>%
  group_by(NAME_1) %>%
  mutate(name1_id = cur_group_id())%>%
  ungroup()%>%
  mutate(adm1_time = case_when(
    iso %in% countries_adm1 ~ name1_id * 10000 + round,
    TRUE ~ NA_integer_
  ))%>%
mutate(adm1_time = as.integer(as.factor(adm1_time)))%>%
mutate(adm2_time = case_when(
    iso %in% countries_adm2 ~ name2_id * 10000 + round,
    TRUE ~ NA_integer_
  ))%>%
mutate(adm2_time = as.integer(as.factor(adm2_time)))

data_final%<>%
  mutate(country_round=as.numeric(paste0(round,ccode)))%>%
  mutate(region_time = case_when(
    iso %in% countries_adm1 ~ name1_id * 10000 + round, 
    iso %in% countries_adm2 ~ name2_id * 10000 + round,
    TRUE ~ NA_integer_
  ))%>%
  mutate(region_time = as.integer(as.factor(region_time)))

saveRDS(data_final, file="data/data_rds/data_final.rds")
write_dta(data_final, "data/data_dta/data_final.dta")
```


```{r}
library(ggplot2)
library(dplyr)
library(maps)

# Mapping of ISO codes to country names
iso_to_country <- data.frame(
  iso = c("AGO", "BDI", "BEN", "BFA", "BWA", "CIV", "CMR", "CPV", "DZA", "EGY", 
          "ETH", "GAB", "GHA", "GIN", "GMB", "KEN", "LBR", "LSO", "MAR", "MDG", 
          "MLI", "MOZ", "MUS", "MWI", "NAM", "NER", "NGA", "SDN", "SEN", "SLE", 
          "STP", "SWZ", "TGO", "TUN", "TZA", "UGA", "ZAF", "ZMB", "ZWE"),
  country = c("Angola", "Burundi", "Benin", "Burkina Faso", "Botswana", "Ivory Coast", 
              "Cameroon", "Cape Verde", "Algeria", "Egypt", "Ethiopia", "Gabon", 
              "Ghana", "Guinea", "Gambia", "Kenya", "Liberia", "Lesotho", "Morocco", 
              "Madagascar", "Mali", "Mozambique", "Mauritius", "Malawi", "Namibia", 
              "Niger", "Nigeria", "Sudan", "Senegal", "Sierra Leone", "Sao Tome and Principe", 
              "Eswatini", "Togo", "Tunisia", "Tanzania", "Uganda", "South Africa", 
              "Zambia", "Zimbabwe")
)

# Count observations for each country based on ISO codes
country_counts <- data_final_adm %>%
  group_by(iso) %>%
  summarize(observation_count = n())

# Filter countries with at least 1000 observations and match with ISO codes
highlight_countries <- country_counts %>%
  filter(observation_count >= 1000, iso %in% iso_to_country$iso) %>%
  pull(iso)

cty <- iso_to_country%>%
  pull(country)

# Get the world map data
africa_map <- map_data("world")%>%
  filter(region%in%cty)

# Add a column for highlighting based on country names
africa_map <- africa_map %>%
  left_join(iso_to_country, by = c("region" = "country")) %>%
  mutate(highlight = ifelse(iso %in% highlight_countries, "Yes", "No"))

# Plot
ggplot() +
  geom_polygon(data = africa_map, aes(x = long, y = lat, group = group, fill = highlight), 
               color = "black") +
  scale_fill_manual(values = c("Yes" = "lightblue", "No" = "gray"), guide = "none") +
  labs(title = "Map of Africa: Countries with At Least 1000 Observations Highlighted") +
  theme_minimal()

```


```{r}

afro_diff <- anti_join(afro_stack, data_final)

afro_diff%>%
  distinct(iso)

afro_diff %>%
  select(latitude, longitude)%>%
  View()

data_final%>%
  select(dist_cap_log, dist_ncap_log, dist_sndncap_log)%>%
  summary()
  
```


```{r}
gov_index <- read_excel("data/data_raw/gov_index.xlsx")%>%
  rename(iso=ISO)
polstab_index <- read_excel("data/data_raw/polstab_index.xlsx")%>%
  rename(iso=ISO)
reg_index <- read_excel("data/data_raw/reg_index.xlsx")%>%
  rename(iso=ISO)
rule_index <- read_excel("data/data_raw/rule_index.xlsx")%>%
  rename(iso=ISO)
voiceac_index <- read_excel("data/data_raw/voiceac_index.xlsx")%>%
  rename(iso=ISO)


vdem <- readRDS("data/data_raw/V-Dem-CY-Full+Others-v13.rds")

```

```{r}
data_final_adm%>% filter(iso=="BEN") %>% select(pop_adm1, pop_adm2, pop_adm3)%>%summary()

data_final_adm %>% select(gg_adm1_pot, round)%>%filter(round==6)%>%summary()

data_final_adm%>%filter(iso=="BEN")%>%select(iso, round, gg_adm1_pot, NAME_1)%>%View()
```


```{r}
ggg_stack <- readRDS("data/data_rds/ggg_stack.rds")

ggg_cty<-ggg_stack%>%distinct(iso)%>%pull(iso)

all_rounds <- seq(min(ggg_stack$round, na.rm = TRUE), max(ggg_stack$round, na.rm = TRUE), by = 1)

for (country in ggg_cty) {
  ggg_stack %>%
    filter(iso == country) %>%
    group_by(round) %>%
    summarize(
      ggg_adm1_mean = mean(ggg_adm1_pot, na.rm = TRUE),
      ggg_adm2_mean = mean(ggg_adm2_pot, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    complete(round = all_rounds, fill = list(ggg_adm1_mean = NA, ggg_adm2_mean = NA)) %>%  # Fill missing rounds with NA
    ggplot(aes(x = round)) +
    geom_line(aes(y = ggg_adm1_mean), size = 1, color = "blue") +
    geom_point(aes(y = ggg_adm1_mean), size = 2, color = "blue") +
    geom_line(aes(y = ggg_adm2_mean), size = 1, color = "red") +
    geom_point(aes(y = ggg_adm2_mean), size = 2, color = "red") +
    labs(
      title = paste("Evolution of ggg_adm1_pot and ggg_adm2_pot Across Rounds for", country),
      x = "Round",
      y = "Mean Values"
    ) +
    scale_y_continuous(limits = c(0, 1)) +  # Fixed y-axis scale between 0 and 1
    theme_minimal() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 16),
      axis.title = element_text(size = 14),
      legend.position = "none"
    ) -> p
  print(p)
}
```




```{r}
setwd("~/working_paper/trust/")
getwd()
```

```{r packages, echo=FALSE, }
library(haven)
library(dplyr)
select <- dplyr::select
library(magrittr)
library(sf)
```

```{r}
countries <- c("BEN", "BFA", "BWA", "CIV", "CMR", "GIN", "LBR", "MLI", "NAM", "NER", "SLE", "GHA", "KEN", "MOZ", "MWI", "NGA", "TZA", "UGA", "ZMB", "ZWE")

data_final <- readRDS("data/data_rds/data_final.rds")

data_final_sf <- subset(data_final, select = c("id_unique","iso","latitude","longitude"))

data_final_sf <- st_as_sf(data_final_sf, coords = c("longitude", "latitude"), crs = 4326)

result <- list()

for (country in countries) {
  shapefile <- file.path("C:/Users/Redha CHABA/Documents/working_paper/trust/data/data_raw/road_shp", paste0("routes_", country, ".shp"))
  
  if (file.exists(shapefile)) {
    roads_sf <- st_read(shapefile)
    roads_sf <- st_transform(roads_sf, st_crs(data_final_sf))
    
    data_final_sf$distance_to_road <- st_distance(data_final_sf, roads_sf) %>% apply(1, min)
    
    country_data_result <- as.data.frame(data_final_sf)
    country_data_result <- country_data_result %>%
      select(id_unique, distance_to_road)
    
    result[[country]] <- country_data_result
  } else {
    warning(paste("Shapefile not found for country:", country))
  }
}

# Combine results into a single data frame
result_combined <- do.call(rbind, lapply(names(result), function(country) {
  cbind(result[[country]], country = country)
}))

final_result_road <- do.call(rbind, result)

final_df6 <- merge(final_df6,final_result_road, by="id_unique")

remove(bdd, country_data, country_data_result, country_data_sf, result, roads_sf, countries, ISO, shapefile)

```

```{r}
tiff_file <- "data/data_raw/geography/desert/desert.tif"

desert_wgs84 <- rast(tiff_file)

print(desert_wgs84)

africa_extent <- ext(-30, 60, -40, 40)

desert_africa <- crop(desert_wgs84, africa_extent)

binary_raster <- ifel(!is.na(desert_africa), 1, 0)

print(binary_raster)

plot(binary_raster, main = "Desert Map", col = rev(heat.colors(100)))

desert_adm1_df <- data.frame()

for (country in cty_adm1) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_1.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(binary_raster), crs(country_shp))) {
    country_shp <- project(country_shp, crs(binary_raster))
  }
  
  binary_raster_cropped <- crop(binary_raster, country_shp)
  binary_raster_masked <- mask(binary_raster_cropped, country_shp)
  
  desert_adm1 <- exactextractr::exact_extract(binary_raster_masked, regions, 'mean')
  
  regions$desert_adm1 <- desert_adm1
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, desert_adm1)
  
  desert_adm1_df <- rbind(desert_adm1_df, country_results)
}

desert_adm1_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(desert_adm1_df))

saveRDS(desert_adm1_df, file="data/data_rds/geo_ctrl/desert_adm1.rds")


desert_adm2_df <- data.frame()

for (country in cty_adm2) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_2.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(binary_raster), crs(country_shp))) {
    country_shp <- project(country_shp, crs(binary_raster))
  }
  
  binary_raster_cropped <- crop(binary_raster, country_shp)
  binary_raster_masked <- mask(binary_raster_cropped, country_shp)
  
  desert_adm2 <- exactextractr::exact_extract(binary_raster_masked, regions, 'mean')
  
  regions$desert_adm2 <- desert_adm2
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, NAME_2, desert_adm2)
  
  desert_adm2_df <- rbind(desert_adm2_df, country_results)
}

desert_adm2_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(desert_adm2_df))

saveRDS(desert_adm2_df, file="data/data_rds/geo_ctrl/desert_adm2.rds")
```

```{r}
tiff_file <- "data/data_raw/geography/elevation/elevation.tif"

elevation_wgs84 <- rast(tiff_file)

print(elevation_wgs84)

plot(elevation_wgs84, main = "Elevation Map", col = terrain.colors(100), breaks = seq(-1000, 3000, by = 100))

elevation_adm1_df <- data.frame()

for (country in cty_adm1) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_1.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(elevation_wgs84), crs(country_shp))) {
    country_shp <- project(country_shp, crs(elevation_wgs84))
  }
  
  elevation_wgs84_cropped <- crop(elevation_wgs84, country_shp)
  elevation_wgs84_masked <- mask(elevation_wgs84_cropped, country_shp)
  
  elevation_adm1 <- exactextractr::exact_extract(elevation_wgs84_masked, regions, 'mean')
  
  regions$elevation_adm1 <- elevation_adm1
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, elevation_adm1)
  
  elevation_adm1_df <- rbind(elevation_adm1_df, country_results)
}

elevation_adm1_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(elevation_adm1_df))

saveRDS(elevation_adm1_df, file="data/data_rds/geo_ctrl/elevation_adm1.rds")

elevation_adm2_df <- data.frame()

for (country in cty_adm2) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_2.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(elevation_wgs84), crs(country_shp))) {
    country_shp <- project(country_shp, crs(elevation_wgs84))
  }
  
  elevation_wgs84_cropped <- crop(elevation_wgs84, country_shp)
  elevation_wgs84_masked <- mask(elevation_wgs84_cropped, country_shp)
  
  elevation_adm2 <- exactextractr::exact_extract(elevation_wgs84_masked, regions, 'mean')
  
  regions$elevation_adm2 <- elevation_adm2
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, NAME_2, elevation_adm2)
  
  elevation_adm2_df <- rbind(elevation_adm2_df, country_results)
}

elevation_adm2_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(elevation_adm2_df))

saveRDS(elevation_adm2_df, file="data/data_rds/geo_ctrl/elevation_adm2.rds")
```

```{r}
library(viridis)

tiff_file <- "data/data_raw/geography/precipitation/CHELSA_bio12_1981-2010_V.2.1.tif"

precipitation_wgs84 <- rast(tiff_file)

print(precipitation_wgs84)

africa_extent <- ext(-30, 60, -40, 40)

precipitation_africa <- crop(precipitation_wgs84, africa_extent)

plot(precipitation_africa, main = "Precipitation Map of Africa", col = rev(viridis(100)))

precipitation_adm1_df <- data.frame()

for (country in cty_adm1) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_1.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(precipitation_wgs84), crs(country_shp))) {
    country_shp <- project(country_shp, crs(precipitation_wgs84))
  }
  
  precipitation_wgs84_cropped <- crop(precipitation_wgs84, country_shp)
  precipitation_wgs84_masked <- mask(precipitation_wgs84_cropped, country_shp)
  
  precipitation_adm1 <- exactextractr::exact_extract(precipitation_wgs84_masked, regions, 'mean')
  
  regions$precipitation_adm1 <- precipitation_adm1
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, precipitation_adm1)
  
  precipitation_adm1_df <- rbind(precipitation_adm1_df, country_results)
}

precipitation_adm1_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(precipitation_adm1_df))

saveRDS(precipitation_adm1_df, file="data/data_rds/geo_ctrl/precipitation_adm1.rds")


precipitation_adm2_df <- data.frame()

for (country in cty_adm2) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_2.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(precipitation_wgs84), crs(country_shp))) {
    country_shp <- project(country_shp, crs(precipitation_wgs84))
  }
  
  precipitation_wgs84_cropped <- crop(precipitation_wgs84, country_shp)
  precipitation_wgs84_masked <- mask(precipitation_wgs84_cropped, country_shp)
  
  precipitation_adm2 <- exactextractr::exact_extract(precipitation_wgs84_masked, regions, 'mean')
  
  regions$precipitation_adm2 <- precipitation_adm2
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, NAME_2, precipitation_adm2)
  
  precipitation_adm2_df <- rbind(precipitation_adm2_df, country_results)
}

precipitation_adm2_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(precipitation_adm2_df))

saveRDS(precipitation_adm2_df, file="data/data_rds/geo_ctrl/precipitation_adm2.rds")
```

```{r}
shapefile_directory <- "data/data_raw/gadm/"

shapefile_names <- list.files(shapefile_directory, pattern = "*_2.shp", full.names = TRUE)

adm2_shapefiles <- lapply(shapefile_names, st_read)
adm2_combined <- do.call(rbind, adm2_shapefiles)

adm2_combined_merged <- merge(adm2_combined, precipitation_adm2, by.x = "NAME_2", by.y = "NAME_2", all.x = TRUE)

library(ggplot2)

ggplot() +
  geom_sf(data = adm2_combined_merged, aes(fill = precipitation_adm2), color = "black", size = 0.25) +
  scale_fill_viridis(name = "Precipitation (mm)", option = "plasma", na.value = "grey") +
  labs(title = "Precipitation Map of Africa",
       subtitle = "Regional Precipitation Values") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5, size = 12),
    legend.position = "bottom"
  )

```


```{r}
tiff_file <- "data/data_raw/geography/temperature/CHELSA_bio1_1981-2010_V.2.1.tif"

temp_mean_wgs84 <- rast(tiff_file)

print(temp_mean_wgs84)

africa_extent <- ext(-30, 60, -40, 40)

temp_mean_africa <- crop(temp_mean_wgs84, africa_extent)

plot(temp_mean_africa, main = "temp_mean Map of Africa", col = rev(heat.colors(100)))

temp_mean_adm1_df <- data.frame()

for (country in cty_adm1) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_1.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(temp_mean_wgs84), crs(country_shp))) {
    country_shp <- project(country_shp, crs(temp_mean_wgs84))
  }
  
  temp_mean_wgs84_cropped <- crop(temp_mean_wgs84, country_shp)
  temp_mean_wgs84_masked <- mask(temp_mean_wgs84_cropped, country_shp)
  
  temp_mean_adm1 <- exactextractr::exact_extract(temp_mean_wgs84_masked, regions, 'mean')
  
  regions$temp_mean_adm1 <- temp_mean_adm1
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, temp_mean_adm1)
  
  temp_mean_adm1_df <- rbind(temp_mean_adm1_df, country_results)
}

temp_mean_adm1_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(temp_mean_adm1_df))

saveRDS(temp_mean_adm1_df, file="data/data_rds/geo_ctrl/temp_mean_adm1.rds")


temp_mean_adm2_df <- data.frame()

for (country in cty_adm2) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_2.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(temp_mean_wgs84), crs(country_shp))) {
    country_shp <- project(country_shp, crs(temp_mean_wgs84))
  }
  
  temp_mean_wgs84_cropped <- crop(temp_mean_wgs84, country_shp)
  temp_mean_wgs84_masked <- mask(temp_mean_wgs84_cropped, country_shp)
  
  temp_mean_adm2 <- exactextractr::exact_extract(temp_mean_wgs84_masked, regions, 'mean')
  
  regions$temp_mean_adm2 <- temp_mean_adm2
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, NAME_2, temp_mean_adm2)
  
  temp_mean_adm2_df <- rbind(temp_mean_adm2_df, country_results)
}

temp_mean_adm2_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(temp_mean_adm2_df))

saveRDS(temp_mean_adm2_df, file="data/data_rds/geo_ctrl/temp_mean_adm2.rds")
```

```{r}
tiff_file <- "data/data_raw/geography/temperature/CHELSA_bio5_1981-2010_V.2.1.tif"

temp_max_wgs84 <- rast(tiff_file)

print(temp_max_wgs84)

africa_extent <- ext(-30, 60, -40, 40)

temp_max_africa <- crop(temp_max_wgs84, africa_extent)

plot(temp_max_africa, main = "temp_max Map of Africa", col = rev(heat.colors(100)), breaks = seq(0, 50, by = 1))

temp_max_adm1_df <- data.frame()

for (country in cty_adm1) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_1.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(temp_max_wgs84), crs(country_shp))) {
    country_shp <- project(country_shp, crs(temp_max_wgs84))
  }
  
  temp_max_wgs84_cropped <- crop(temp_max_wgs84, country_shp)
  temp_max_wgs84_masked <- mask(temp_max_wgs84_cropped, country_shp)
  
  temp_max_adm1 <- exactextractr::exact_extract(temp_max_wgs84_masked, regions, 'mean')
  
  regions$temp_max_adm1 <- temp_max_adm1
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, temp_max_adm1)
  
  temp_max_adm1_df <- rbind(temp_max_adm1_df, country_results)
}

temp_max_adm1_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(temp_max_adm1_df))

saveRDS(temp_max_adm1_df, file="data/data_rds/geo_ctrl/temp_max_adm1.rds")

temp_max_adm2_df <- data.frame()

for (country in cty_adm2) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_2.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(temp_max_wgs84), crs(country_shp))) {
    country_shp <- project(country_shp, crs(temp_max_wgs84))
  }
  
  temp_max_wgs84_cropped <- crop(temp_max_wgs84, country_shp)
  temp_max_wgs84_masked <- mask(temp_max_wgs84_cropped, country_shp)
  
  temp_max_adm2 <- exactextractr::exact_extract(temp_max_wgs84_masked, regions, 'mean')
  
  regions$temp_max_adm2 <- temp_max_adm2
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, NAME_2, temp_max_adm2)
  
  temp_max_adm2_df <- rbind(temp_max_adm2_df, country_results)
}

temp_max_adm2_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(temp_max_adm2_df))

saveRDS(temp_max_adm2_df, file="data/data_rds/geo_ctrl/temp_max_adm2.rds")
```

```{r}
tiff_file <- "data/data_raw/geography/temperature/CHELSA_bio6_1981-2010_V.2.1.tif"

temp_min_wgs84 <- rast(tiff_file)

print(temp_min_wgs84)

africa_extent <- ext(-30, 60, -40, 40)

temp_min_africa <- crop(temp_min_wgs84, africa_extent)

plot(temp_min_africa, main = "temp_min Map of Africa", col = viridis(100), breaks = seq(-20, 30, by = 1))

temp_min_adm1_df <- data.frame()

for (country in cty_adm1) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_1.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(temp_min_wgs84), crs(country_shp))) {
    country_shp <- project(country_shp, crs(temp_min_wgs84))
  }
  
  temp_min_wgs84_cropped <- crop(temp_min_wgs84, country_shp)
  temp_min_wgs84_masked <- mask(temp_min_wgs84_cropped, country_shp)
  
  temp_min_adm1 <- exactextractr::exact_extract(temp_min_wgs84_masked, regions, 'mean')
  
  regions$temp_min_adm1 <- temp_min_adm1
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, temp_min_adm1)
  
  temp_min_adm1_df <- rbind(temp_min_adm1_df, country_results)
}

temp_min_adm1_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(temp_min_adm1_df))

saveRDS(temp_min_adm1_df, file="data/data_rds/geo_ctrl/temp_min_adm1.rds")


temp_min_adm2_df <- data.frame()

for (country in cty_adm2) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_2.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(temp_min_wgs84), crs(country_shp))) {
    country_shp <- project(country_shp, crs(temp_min_wgs84))
  }
  
  temp_min_wgs84_cropped <- crop(temp_min_wgs84, country_shp)
  temp_min_wgs84_masked <- mask(temp_min_wgs84_cropped, country_shp)
  
  temp_min_adm2 <- exactextractr::exact_extract(temp_min_wgs84_masked, regions, 'mean')
  
  regions$temp_min_adm2 <- temp_min_adm2
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, NAME_2, temp_min_adm2)
  
  temp_min_adm2_df <- rbind(temp_min_adm2_df, country_results)
}

temp_min_adm2_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(temp_min_adm2_df))

saveRDS(temp_min_adm2_df, file="data/data_rds/geo_ctrl/temp_min_adm2.rds")
```

```{r}
tiff_file <- "data/data_raw/geography/mountain/k3binary.tif"

mountain_wgs84 <- rast(tiff_file)

print(mountain_wgs84)

africa_extent <- ext(-30, 60, -40, 40)

mountain_africa <- crop(mountain_wgs84, africa_extent)

binary_raster <- ifel(!is.na(mountain_africa), 1, 0)

plot(binary_raster, main = "mountain Map of Africa", col = viridis(100))

mountain_adm1_df <- data.frame()

for (country in cty_adm1) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_1.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(binary_raster), crs(country_shp))) {
    country_shp <- project(country_shp, crs(binary_raster))
  }
  
  binary_raster_cropped <- crop(binary_raster, country_shp)
  binary_raster_masked <- mask(binary_raster_cropped, country_shp)
  
  mountain_adm1 <- exactextractr::exact_extract(binary_raster_masked, regions, 'mean')
  
  regions$mountain_adm1 <- mountain_adm1
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, mountain_adm1)
  
  mountain_adm1_df <- rbind(mountain_adm1_df, country_results)
}

mountain_adm1_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(mountain_adm1_df))

saveRDS(mountain_adm1_df, file="data/data_rds/geo_ctrl/mountain_adm1.rds")


mountain_adm2_df <- data.frame()

for (country in cty_adm2) {
  
  shapefile <- paste0("data/data_raw/gadm/gadm41_", country, "_2.shp")
  regions <- st_read(shapefile) %>% st_make_valid()
  
  shapefile_path <- paste0("data/data_raw/gadm/gadm41_", country, "_0.shp")
  country_shp <- vect(shapefile_path)
  
  if (!identical(crs(binary_raster), crs(country_shp))) {
    country_shp <- project(country_shp, crs(binary_raster))
  }
  
  binary_raster_cropped <- crop(binary_raster, country_shp)
  binary_raster_masked <- mask(binary_raster_cropped, country_shp)
  
  mountain_adm2 <- exactextractr::exact_extract(binary_raster_masked, regions, 'mean')
  
  regions$mountain_adm2 <- mountain_adm2
  
  country_results <- regions %>%
    as.data.frame() %>%
    rename(iso = GID_0) %>%
    select(iso, NAME_1, NAME_2, mountain_adm2)
  
  mountain_adm2_df <- rbind(mountain_adm2_df, country_results)
}

mountain_adm2_df %<>%
  mutate(across(everything(), ~ ifelse(is.nan(.), NA, .)))

print(glimpse(mountain_adm2_df))

saveRDS(mountain_adm2_df, file="data/data_rds/geo_ctrl/mountain_adm2.rds")
```

```{r}
desert_adm1 <- readRDS("data/data_rds/geo_ctrl/desert_adm1.rds")
desert_adm2 <- readRDS("data/data_rds/geo_ctrl/desert_adm2.rds")

desert <- merge(desert_adm1, desert_adm2, by = c("iso", "NAME_1"), all = TRUE)

rm(desert_adm1, desert_adm2)

rounds <- data.frame(round = rep(5:8, each = nrow(desert)))

expanded_data <- desert[rep(1:nrow(desert), times = 4), ]

expanded_data$round <- rounds$round

expanded_data <- expanded_data %>% distinct(iso, NAME_1, NAME_2, round, .keep_all = TRUE)

data_geo <- expanded_data

rm(desert)

elevation_adm1 <- readRDS("data/data_rds/geo_ctrl/elevation_adm1.rds")
elevation_adm2 <- readRDS("data/data_rds/geo_ctrl/elevation_adm2.rds")

elevation <- merge(elevation_adm1, elevation_adm2, by = c("iso", "NAME_1"), all = TRUE)

rm(elevation_adm1, elevation_adm2)

rounds <- data.frame(round = rep(5:8, each = nrow(elevation)))

expanded_data <- elevation[rep(1:nrow(elevation), times = 4), ]

expanded_data$round <- rounds$round

expanded_data <- expanded_data %>% distinct(iso, NAME_1, NAME_2, round, .keep_all = TRUE)

data_geo %<>% left_join(expanded_data, by=c("iso", "NAME_1", "NAME_2", "round"))

rm(elevation)

mountain_adm1 <- readRDS("data/data_rds/geo_ctrl/mountain_adm1.rds")
mountain_adm2 <- readRDS("data/data_rds/geo_ctrl/mountain_adm2.rds")

mountain <- merge(mountain_adm1, mountain_adm2, by = c("iso", "NAME_1"), all = TRUE)

rm(mountain_adm1, mountain_adm2)

rounds <- data.frame(round = rep(5:8, each = nrow(mountain)))

expanded_data <- mountain[rep(1:nrow(mountain), times = 4), ]

expanded_data$round <- rounds$round

expanded_data <- expanded_data %>% distinct(iso, NAME_1, NAME_2, round, .keep_all = TRUE)

data_geo %<>% left_join(expanded_data, by=c("iso", "NAME_1", "NAME_2", "round"))

rm(mountain)

precipitation_adm1 <- readRDS("data/data_rds/geo_ctrl/precipitation_adm1.rds")
precipitation_adm2 <- readRDS("data/data_rds/geo_ctrl/precipitation_adm2.rds")

precipitation <- merge(precipitation_adm1, precipitation_adm2, by = c("iso", "NAME_1"), all = TRUE)

rm(precipitation_adm1, precipitation_adm2)

rounds <- data.frame(round = rep(5:8, each = nrow(precipitation)))

expanded_data <- precipitation[rep(1:nrow(precipitation), times = 4), ]

expanded_data$round <- rounds$round

expanded_data <- expanded_data %>% distinct(iso, NAME_1, NAME_2, round, .keep_all = TRUE)

data_geo %<>% left_join(expanded_data, by=c("iso", "NAME_1", "NAME_2", "round"))

rm(precipitation)

temp_max_adm1 <- readRDS("data/data_rds/geo_ctrl/temp_max_adm1.rds")
temp_max_adm2 <- readRDS("data/data_rds/geo_ctrl/temp_max_adm2.rds")

temp_max <- merge(temp_max_adm1, temp_max_adm2, by = c("iso", "NAME_1"), all = TRUE)

rm(temp_max_adm1, temp_max_adm2)

rounds <- data.frame(round = rep(5:8, each = nrow(temp_max)))

expanded_data <- temp_max[rep(1:nrow(temp_max), times = 4), ]

expanded_data$round <- rounds$round

expanded_data <- expanded_data %>% distinct(iso, NAME_1, NAME_2, round, .keep_all = TRUE)

data_geo %<>% left_join(expanded_data, by=c("iso", "NAME_1", "NAME_2", "round"))

rm(temp_max)

temp_min_adm1 <- readRDS("data/data_rds/geo_ctrl/temp_min_adm1.rds")
temp_min_adm2 <- readRDS("data/data_rds/geo_ctrl/temp_min_adm2.rds")

temp_min <- merge(temp_min_adm1, temp_min_adm2, by = c("iso", "NAME_1"), all = TRUE)

rm(temp_min_adm1, temp_min_adm2)

rounds <- data.frame(round = rep(5:8, each = nrow(temp_min)))

expanded_data <- temp_min[rep(1:nrow(temp_min), times = 4), ]

expanded_data$round <- rounds$round

expanded_data <- expanded_data %>% distinct(iso, NAME_1, NAME_2, round, .keep_all = TRUE)

data_geo %<>% left_join(expanded_data, by=c("iso", "NAME_1", "NAME_2", "round"))

rm(temp_min)

temp_mean_adm1 <- readRDS("data/data_rds/geo_ctrl/temp_mean_adm1.rds")
temp_mean_adm2 <- readRDS("data/data_rds/geo_ctrl/temp_mean_adm2.rds")

temp_mean <- merge(temp_mean_adm1, temp_mean_adm2, by = c("iso", "NAME_1"), all = TRUE)

rm(temp_mean_adm1, temp_mean_adm2)

rounds <- data.frame(round = rep(5:8, each = nrow(temp_mean)))

expanded_data <- temp_mean[rep(1:nrow(temp_mean), times = 4), ]

expanded_data$round <- rounds$round

expanded_data <- expanded_data %>% distinct(iso, NAME_1, NAME_2, round, .keep_all = TRUE)

data_geo %<>% left_join(expanded_data, by=c("iso", "NAME_1", "NAME_2", "round"))

rm(temp_mean)

data_final_r <- readRDS("data/data_rds/data_final_r.rds")

data_final_r %<>% left_join(data_geo, by=c("iso", "NAME_1", "NAME_2", "round"))

countries_adm1 <- c("GHA","KEN","MOZ", "MWI","NGA","TZA","UGA","ZMB", "ZWE")
countries_adm2 <- c("BEN", "BFA", "BWA", "CIV", "CMR", "GIN", "LBR", "MLI", "NAM", "NER", "SLE")

data_final_r %<>%
mutate(desert_region = case_when(
    iso %in% countries_adm1 ~ desert_adm1,
    iso %in% countries_adm2 ~ desert_adm2, 
    TRUE ~ NA_integer_
  ))%>%
mutate(elevation_region = case_when(
    iso %in% countries_adm1 ~ elevation_adm1,
    iso %in% countries_adm2 ~ elevation_adm2, 
    TRUE ~ NA_integer_
  ))%>%
mutate(mountain_region = case_when(
    iso %in% countries_adm1 ~ mountain_adm1,
    iso %in% countries_adm2 ~ mountain_adm2, 
    TRUE ~ NA_integer_
  ))%>%
mutate(precipitation_region = case_when(
    iso %in% countries_adm1 ~ precipitation_adm1,
    iso %in% countries_adm2 ~ precipitation_adm2, 
    TRUE ~ NA_integer_
  ))%>%
mutate(temp_max_region = case_when(
    iso %in% countries_adm1 ~ temp_max_adm1,
    iso %in% countries_adm2 ~ temp_max_adm2, 
    TRUE ~ NA_integer_
  ))%>%
mutate(temp_min_region = case_when(
    iso %in% countries_adm1 ~ temp_min_adm1,
    iso %in% countries_adm2 ~ temp_min_adm2, 
    TRUE ~ NA_integer_
  ))%>%
mutate(temp_mean_region = case_when(
    iso %in% countries_adm1 ~ temp_mean_adm1,
    iso %in% countries_adm2 ~ temp_mean_adm2, 
    TRUE ~ NA_integer_
  ))


data_final <- readRDS("data/data_rds/data_27_02_25.rds")

data_final%<>%
  ungroup()

data_final%<>%
  mutate(desert_region_tv=desert_region*tv,
         mountain_region_tv=mountain_region*tv,
         elevation_region_tv=elevation_region*tv)


saveRDS(data_final, file="data/data_rds/data_final.rds")

write_dta(data_final, "data/data_dta/data_final.dta")
```

```{r}
vdem <- readRDS("data/data_raw/V-Dem-CY-Full+Others-v13.rds")

vdem%<>%
  select(country_text_id, year, v2xedvd_inpt, v2x_polyarchy, v2xedvd_me_cent, v2medstateprint, v2medstatebroad, v2medpolstate, v2medpolnonstate, e_v2x_freexp_altinf_3C, e_v2x_freexp_altinf_4C, e_v2x_freexp_altinf_5C, v2x_freexp, v2xme_altinf, e_polity2)

vdem%<>%
  filter(country_text_id %in% countries)

vdem%<>%
  rename(iso=country_text_id)%>%
    mutate(round=case_when(between(year, 2011, 2013)~5,
                         between(year, 2014, 2015)~6,
                         between(year, 2016, 2018)~7,
                         between(year, 2019, 2021)~8,
         TRUE~NA_integer_))

vdem %<>%
  group_by(iso, round) %>%
  filter(!is.na(round)) %>%
  mutate(
    v2xedvd_inpt_mean2 = ifelse(all(is.na(v2xedvd_inpt)), NA_integer_, mean(v2xedvd_inpt, na.rm = TRUE)),
    v2x_polyarchy_mean2 = ifelse(all(is.na(v2x_polyarchy)), NA_integer_, mean(v2x_polyarchy, na.rm = TRUE)),
    v2xedvd_me_cent_mean2 = ifelse(all(is.na(v2xedvd_me_cent)), NA_integer_, mean(v2xedvd_me_cent, na.rm = TRUE)),
    v2medstateprint_mean2 = ifelse(all(is.na(v2medstateprint)), NA_integer_, mean(v2medstateprint, na.rm = TRUE)),
    v2medstatebroad_mean2 = ifelse(all(is.na(v2medstatebroad)), NA_integer_, mean(v2medstatebroad, na.rm = TRUE)),
    v2medpolstate_mean2 = ifelse(all(is.na(v2medpolstate)), NA_integer_, mean(v2medpolstate, na.rm = TRUE)),
    v2medpolnonstate_mean2 = ifelse(all(is.na(v2medpolnonstate)), NA_integer_, mean(v2medpolnonstate, na.rm = TRUE)),
    e_v2x_freexp_altinf_3C_mean2 = ifelse(all(is.na(e_v2x_freexp_altinf_3C)), NA_integer_, mean(e_v2x_freexp_altinf_3C, na.rm = TRUE)),
    e_v2x_freexp_altinf_4C_mean2 = ifelse(all(is.na(e_v2x_freexp_altinf_4C)), NA_integer_, mean(e_v2x_freexp_altinf_4C, na.rm = TRUE)),
    e_v2x_freexp_altinf_5C_mean2 = ifelse(all(is.na(e_v2x_freexp_altinf_5C)), NA_integer_, mean(e_v2x_freexp_altinf_5C, na.rm = TRUE)),
    v2x_freexp_mean2 = ifelse(all(is.na(v2x_freexp)), NA_integer_, mean(v2x_freexp, na.rm = TRUE)),
    v2xme_altinf_mean2 = ifelse(all(is.na(v2xme_altinf)), NA_integer_, mean(v2xme_altinf, na.rm = TRUE)),
    e_polity2_mean2 = ifelse(all(is.na(e_polity2)), NA_integer_, mean(e_polity2, na.rm = TRUE))
  ) %>%
  ungroup()


vdem%<>%
  mutate(e_polity2_med_all=ifelse(is.na(round), NA_integer_, median(e_polity2, na.rm=TRUE)))

vdem%<>%
  select(iso, round, v2xedvd_inpt_mean2, v2x_polyarchy_mean2, v2xedvd_me_cent_mean2, v2medstateprint_mean2, v2medstatebroad_mean2, v2medpolstate_mean2, v2medpolnonstate_mean2, e_v2x_freexp_altinf_3C_mean2, e_v2x_freexp_altinf_4C_mean2, e_v2x_freexp_altinf_5C_mean2, v2x_freexp_mean2, v2xme_altinf_mean2, e_polity2_mean2, e_polity2_med_all)%>%
    distinct(iso, round, .keep_all = TRUE)

data_final %<>% left_join(vdem, by=c("iso", "round"))

```


```{r}
library(readxl)
library(tidyr)

data_final <- readRDS("data/data_rds/data_final.rds")

countries <- data_final %>% filter(spl == 1) %>% pull(iso) %>% unique()

wb_gov <- read_excel("data/data_raw/wb_gov/wgidataset.xlsx")

wb_gov %<>%
  select(code, year, indicator, estimate) %>%
  mutate(estimate = na_if(estimate, ".."))

wb_gov %<>%
  pivot_wider(names_from = indicator, values_from = estimate)

wb_gov %<>%
  rename(
    ctrl_corr = cc,
    voice_acc = va,
    pol_stab = pv,
    gov_eff = ge,
    reg_qty = rq,
    rol = rl,
    iso = code
  ) %>%
  mutate(across(c(
    ctrl_corr, voice_acc, pol_stab, gov_eff, reg_qty
  ), as.numeric))


wb_gov %<>%
  mutate(round = case_when(
    between(year, 2011, 2013) ~ 5,
    between(year, 2014, 2015) ~ 6,
    between(year, 2016, 2018) ~ 7,
    between(year, 2019, 2021) ~ 8,
    TRUE ~ NA_integer_
  ))

wb_gov %<>%
  group_by(iso, round) %>%
  filter(!is.na(round)) %>%
  mutate(
    ctrl_corr_mean = ifelse(all(is.na(ctrl_corr)), NA_integer_, mean(ctrl_corr, na.rm = TRUE)),
    voice_acc_mean = ifelse(all(is.na(voice_acc)), NA_integer_, mean(voice_acc, na.rm = TRUE)),
    pol_stab_mean = ifelse(all(is.na(pol_stab)), NA_integer_, mean(pol_stab, na.rm = TRUE)),
    gov_eff_mean = ifelse(all(is.na(gov_eff)), NA_integer_, mean(gov_eff, na.rm = TRUE)),
    reg_qty_mean = ifelse(all(is.na(reg_qty)), NA_integer_, mean(reg_qty, na.rm = TRUE))
  ) %>%
  ungroup()

wb_gov %<>%
  select(
    iso,
    round,
    ctrl_corr_mean,
    voice_acc_mean,
    pol_stab_mean,
    gov_eff_mean,
    reg_qty_mean
  ) %>%
  distinct(iso, round, .keep_all = TRUE)

wb_gov %<>%
  filter(iso %in% countries)
```

