```{r}
setwd("~/Working paper/Trust/Script")
getwd()

```


```{r}
library(dplyr)
select <- dplyr::select
library(magrittr)
library(sf)
#afro_w8 <- sf::st_sf(afro_w8)


afro_w8 <- afro_w8%>%ungroup()

afro_w8%>%
  distinct(cname,ISO,ccode)%>%
  arrange(ISO)%>%
  select(cname)%>%
  print(n=50)

```

```{r}
library(tidyverse)

# Path to the folder containing the files
folder_path <- "C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw"

# List of files in the folder
files <- list.files(folder_path, full.names = TRUE)

# Extract countries and levels from file names
data <- data.frame(file = files) %>%
  mutate(country = str_extract(file, "(?<=_)[A-Z]{3}(?=_\\d)"),
         level = as.integer(str_extract(file, "(?<=_)[0-9]+(?=\\.shp$)"))) %>%
  arrange(country, desc(level)) %>%
  distinct(country, .keep_all = TRUE)

# Count the number of levels for each country
levels_per_country <- data %>%
  group_by(country) %>%
  summarise(number_of_levels = first(level))

# Print the result
print(levels_per_country)

objects <- ls()
objects <- objects[objects != "afro_w8"]

```
**Countries with 3 ADM levels**

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="BEN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_BEN_1.shp")

regions_valid_BEN_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_BEN_1))

result <- st_intersects(panel_sf, regions_valid_BEN_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_BEN_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 <- left_join(afro_w8, result_with_region_1, by = "id_unique")



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="BEN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_BEN_2.shp")

regions_valid_BEN_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_BEN_2))

result <- st_intersects(panel_sf, regions_valid_BEN_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_BEN_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 <- left_join(afro_w8, result_with_region_2, by = "id_unique")



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="BEN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_BEN_3.shp")

regions_valid_BEN_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_BEN_3))

result <- st_intersects(panel_sf, regions_valid_BEN_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_BEN_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 <- left_join(afro_w8, result_with_region_3, by = "id_unique")

objects <- ls()
objects <- objects[objects != "afro_w8"]


```


```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="SEN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_SEN_1.shp")

regions_valid_SEN_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_SEN_1))

result <- st_intersects(panel_sf, regions_valid_SEN_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_SEN_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="SEN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_SEN_2.shp")

regions_valid_SEN_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_SEN_2))

result <- st_intersects(panel_sf, regions_valid_SEN_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_SEN_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="SEN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_SEN_3.shp")

regions_valid_SEN_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_SEN_3))

result <- st_intersects(panel_sf, regions_valid_SEN_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_SEN_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```


```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="BDI") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_BDI_1.shp")

regions_valid_BDI_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_BDI_1))

result <- st_intersects(panel_sf, regions_valid_BDI_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_BDI_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="BDI") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_BDI_2.shp")

regions_valid_BDI_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_BDI_2))

result <- st_intersects(panel_sf, regions_valid_BDI_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_BDI_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="BDI") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_BDI_3.shp")

regions_valid_BDI_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_BDI_3))

result <- st_intersects(panel_sf, regions_valid_BDI_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_BDI_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```


```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="BFA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_BFA_1.shp")

regions_valid_BFA_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_BFA_1))

result <- st_intersects(panel_sf, regions_valid_BFA_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_BFA_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="BFA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_BFA_2.shp")

regions_valid_BFA_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_BFA_2))

result <- st_intersects(panel_sf, regions_valid_BFA_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_BFA_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="BFA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_BFA_3.shp")

regions_valid_BFA_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_BFA_3))

result <- st_intersects(panel_sf, regions_valid_BFA_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_BFA_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="CIV") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_CIV_1.shp")

regions_valid_CIV_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_CIV_1))

result <- st_intersects(panel_sf, regions_valid_CIV_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_CIV_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="CIV") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_CIV_2.shp")

regions_valid_CIV_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_CIV_2))

result <- st_intersects(panel_sf, regions_valid_CIV_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_CIV_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="CIV") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_CIV_3.shp")

regions_valid_CIV_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_CIV_3))

result <- st_intersects(panel_sf, regions_valid_CIV_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_CIV_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="CMR") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_CMR_1.shp")

regions_valid_CMR_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_CMR_1))

result <- st_intersects(panel_sf, regions_valid_CMR_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_CMR_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="CMR") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_CMR_2.shp")

regions_valid_CMR_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_CMR_2))

result <- st_intersects(panel_sf, regions_valid_CMR_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_CMR_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="CMR") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_CMR_3.shp")

regions_valid_CMR_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_CMR_3))

result <- st_intersects(panel_sf, regions_valid_CMR_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_CMR_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="ETH") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_ETH_1.shp")

regions_valid_ETH_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_ETH_1))

result <- st_intersects(panel_sf, regions_valid_ETH_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_ETH_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="ETH") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_ETH_2.shp")

regions_valid_ETH_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_ETH_2))

result <- st_intersects(panel_sf, regions_valid_ETH_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_ETH_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="ETH") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_ETH_3.shp")

regions_valid_ETH_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_ETH_3))

result <- st_intersects(panel_sf, regions_valid_ETH_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_ETH_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="GIN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_GIN_1.shp")

regions_valid_GIN_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_GIN_1))

result <- st_intersects(panel_sf, regions_valid_GIN_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_GIN_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="GIN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_GIN_2.shp")

regions_valid_GIN_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_GIN_2))

result <- st_intersects(panel_sf, regions_valid_GIN_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_GIN_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="GIN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_GIN_3.shp")

regions_valid_GIN_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_GIN_3))

result <- st_intersects(panel_sf, regions_valid_GIN_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_GIN_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="KEN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_KEN_1.shp")

regions_valid_KEN_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_KEN_1))

result <- st_intersects(panel_sf, regions_valid_KEN_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_KEN_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="KEN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_KEN_2.shp")

regions_valid_KEN_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_KEN_2))

result <- st_intersects(panel_sf, regions_valid_KEN_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_KEN_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="KEN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_KEN_3.shp")

regions_valid_KEN_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_KEN_3))

result <- st_intersects(panel_sf, regions_valid_KEN_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_KEN_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="LBR") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_LBR_1.shp")

regions_valid_LBR_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_LBR_1))

result <- st_intersects(panel_sf, regions_valid_LBR_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_LBR_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="LBR") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_LBR_2.shp")

regions_valid_LBR_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_LBR_2))

result <- st_intersects(panel_sf, regions_valid_LBR_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_LBR_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="LBR") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_LBR_3.shp")

regions_valid_LBR_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_LBR_3))

result <- st_intersects(panel_sf, regions_valid_LBR_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_LBR_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```


```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MAR") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MAR_1.shp")

regions_valid_MAR_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MAR_1))

result <- st_intersects(panel_sf, regions_valid_MAR_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_MAR_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MAR") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MAR_2.shp")

regions_valid_MAR_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MAR_2))

result <- st_intersects(panel_sf, regions_valid_MAR_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_MAR_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MAR") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MAR_3.shp")

regions_valid_MAR_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MAR_3))

result <- st_intersects(panel_sf, regions_valid_MAR_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_MAR_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MDG") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MDG_1.shp")

regions_valid_MDG_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MDG_1))

result <- st_intersects(panel_sf, regions_valid_MDG_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_MDG_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MDG") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MDG_2.shp")

regions_valid_MDG_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MDG_2))

result <- st_intersects(panel_sf, regions_valid_MDG_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_MDG_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MDG") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MDG_3.shp")

regions_valid_MDG_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MDG_3))

result <- st_intersects(panel_sf, regions_valid_MDG_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_MDG_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MLI") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MLI_1.shp")

regions_valid_MLI_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MLI_1))

result <- st_intersects(panel_sf, regions_valid_MLI_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_MLI_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MLI") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MLI_2.shp")

regions_valid_MLI_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MLI_2))

result <- st_intersects(panel_sf, regions_valid_MLI_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_MLI_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MLI") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MLI_3.shp")

regions_valid_MLI_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MLI_3))

result <- st_intersects(panel_sf, regions_valid_MLI_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_MLI_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MOZ") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MOZ_1.shp")

regions_valid_MOZ_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MOZ_1))

result <- st_intersects(panel_sf, regions_valid_MOZ_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_MOZ_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MOZ") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MOZ_2.shp")

regions_valid_MOZ_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MOZ_2))

result <- st_intersects(panel_sf, regions_valid_MOZ_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_MOZ_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MOZ") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MOZ_3.shp")

regions_valid_MOZ_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MOZ_3))

result <- st_intersects(panel_sf, regions_valid_MOZ_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_MOZ_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MWI") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MWI_1.shp")

regions_valid_MWI_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MWI_1))

result <- st_intersects(panel_sf, regions_valid_MWI_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_MWI_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MWI") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MWI_2.shp")

regions_valid_MWI_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MWI_2))

result <- st_intersects(panel_sf, regions_valid_MWI_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_MWI_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MWI") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MWI_3.shp")

regions_valid_MWI_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MWI_3))

result <- st_intersects(panel_sf, regions_valid_MWI_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_MWI_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="NER") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_NER_1.shp")

regions_valid_NER_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_NER_1))

result <- st_intersects(panel_sf, regions_valid_NER_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_NER_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="NER") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_NER_2.shp")

regions_valid_NER_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_NER_2))

result <- st_intersects(panel_sf, regions_valid_NER_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_NER_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="NER") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_NER_3.shp")

regions_valid_NER_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_NER_3))

result <- st_intersects(panel_sf, regions_valid_NER_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_NER_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="SDN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_SDN_1.shp")

regions_valid_SDN_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_SDN_1))

result <- st_intersects(panel_sf, regions_valid_SDN_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_SDN_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="SDN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_SDN_2.shp")

regions_valid_SDN_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_SDN_2))

result <- st_intersects(panel_sf, regions_valid_SDN_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_SDN_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="SDN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_SDN_3.shp")

regions_valid_SDN_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_SDN_3))

result <- st_intersects(panel_sf, regions_valid_SDN_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_SDN_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```


```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="SLE") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_SLE_1.shp")

regions_valid_SLE_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_SLE_1))

result <- st_intersects(panel_sf, regions_valid_SLE_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_SLE_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="SLE") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_SLE_2.shp")

regions_valid_SLE_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_SLE_2))

result <- st_intersects(panel_sf, regions_valid_SLE_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_SLE_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="SLE") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_SLE_3.shp")

regions_valid_SLE_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_SLE_3))

result <- st_intersects(panel_sf, regions_valid_SLE_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_SLE_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="TGO") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_TGO_1.shp")

regions_valid_TGO_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_TGO_1))

result <- st_intersects(panel_sf, regions_valid_TGO_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_TGO_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="TGO") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_TGO_2.shp")

regions_valid_TGO_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_TGO_2))

result <- st_intersects(panel_sf, regions_valid_TGO_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_TGO_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="TGO") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_TGO_3.shp")

regions_valid_TGO_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_TGO_3))

result <- st_intersects(panel_sf, regions_valid_TGO_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_TGO_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="TZA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_TZA_1.shp")

regions_valid_TZA_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_TZA_1))

result <- st_intersects(panel_sf, regions_valid_TZA_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_TZA_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="TZA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_TZA_2.shp")

regions_valid_TZA_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_TZA_2))

result <- st_intersects(panel_sf, regions_valid_TZA_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_TZA_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="TZA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_TZA_3.shp")

regions_valid_TZA_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_TZA_3))

result <- st_intersects(panel_sf, regions_valid_TZA_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_TZA_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="UGA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_UGA_1.shp")

regions_valid_UGA_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_UGA_1))

result <- st_intersects(panel_sf, regions_valid_UGA_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_UGA_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="UGA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_UGA_2.shp")

regions_valid_UGA_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_UGA_2))

result <- st_intersects(panel_sf, regions_valid_UGA_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_UGA_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="UGA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_UGA_3.shp")

regions_valid_UGA_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_UGA_3))

result <- st_intersects(panel_sf, regions_valid_UGA_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_UGA_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="ZAF") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_ZAF_1.shp")

regions_valid_ZAF_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_ZAF_1))

result <- st_intersects(panel_sf, regions_valid_ZAF_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_ZAF_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="ZAF") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_ZAF_2.shp")

regions_valid_ZAF_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_ZAF_2))

result <- st_intersects(panel_sf, regions_valid_ZAF_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_ZAF_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="ZAF") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_ZAF_3.shp")

regions_valid_ZAF_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_ZAF_3))

result <- st_intersects(panel_sf, regions_valid_ZAF_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_ZAF_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="ZWE") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_ZWE_1.shp")

regions_valid_ZWE_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_ZWE_1))

result <- st_intersects(panel_sf, regions_valid_ZWE_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_ZWE_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="ZWE") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_ZWE_2.shp")

regions_valid_ZWE_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_ZWE_2))

result <- st_intersects(panel_sf, regions_valid_ZWE_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_ZWE_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))




panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="ZWE") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_ZWE_3.shp")

regions_valid_ZWE_3 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_ZWE_3))

result <- st_intersects(panel_sf, regions_valid_ZWE_3)

result_with_region_3 <- st_join(panel_sf, regions_valid_ZWE_3, join = st_intersects)

result_with_region_3 <- as.data.frame(result_with_region_3)

result_with_region_3%<>%
  select(id_unique, NAME_3)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_3, by = "id_unique")%>%
    mutate(NAME_3= if_else(!is.na(NAME_3.x), NAME_3.x, NAME_3.y))%>%
    select(-c(NAME_3.x, NAME_3.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]



```

**Country with only 2 ADM levels**

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="BWA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_BWA_1.shp")

regions_valid_BWA_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_BWA_1))

result <- st_intersects(panel_sf, regions_valid_BWA_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_BWA_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="BWA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_BWA_2.shp")

regions_valid_BWA_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_BWA_2))

result <- st_intersects(panel_sf, regions_valid_BWA_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_BWA_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="DZA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_DZA_1.shp")

regions_valid_DZA_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_DZA_1))

result <- st_intersects(panel_sf, regions_valid_DZA_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_DZA_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="DZA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_DZA_2.shp")

regions_valid_DZA_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_DZA_2))

result <- st_intersects(panel_sf, regions_valid_DZA_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_DZA_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="EGY") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_EGY_1.shp")

regions_valid_EGY_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_EGY_1))

result <- st_intersects(panel_sf, regions_valid_EGY_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_EGY_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="EGY") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_EGY_2.shp")

regions_valid_EGY_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_EGY_2))

result <- st_intersects(panel_sf, regions_valid_EGY_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_EGY_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="GAB") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_GAB_1.shp")

regions_valid_GAB_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_GAB_1))

result <- st_intersects(panel_sf, regions_valid_GAB_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_GAB_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="GAB") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_GAB_2.shp")

regions_valid_GAB_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_GAB_2))

result <- st_intersects(panel_sf, regions_valid_GAB_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_GAB_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="GHA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_GHA_1.shp")

regions_valid_GHA_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_GHA_1))

result <- st_intersects(panel_sf, regions_valid_GHA_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_GHA_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="GHA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_GHA_2.shp")

regions_valid_GHA_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_GHA_2))

result <- st_intersects(panel_sf, regions_valid_GHA_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_GHA_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="GMB") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_GMB_1.shp")

regions_valid_GMB_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_GMB_1))

result <- st_intersects(panel_sf, regions_valid_GMB_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_GMB_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="GMB") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_GMB_2.shp")

regions_valid_GMB_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_GMB_2))

result <- st_intersects(panel_sf, regions_valid_GMB_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_GMB_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="NAM") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_NAM_1.shp")

regions_valid_NAM_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_NAM_1))

result <- st_intersects(panel_sf, regions_valid_NAM_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_NAM_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="NAM") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_NAM_2.shp")

regions_valid_NAM_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_NAM_2))

result <- st_intersects(panel_sf, regions_valid_NAM_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_NAM_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="NGA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_NGA_1.shp")

regions_valid_NGA_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_NGA_1))

result <- st_intersects(panel_sf, regions_valid_NGA_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_NGA_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="NGA") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_NGA_2.shp")

regions_valid_NGA_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_NGA_2))

result <- st_intersects(panel_sf, regions_valid_NGA_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_NGA_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="STP") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_STP_1.shp")

regions_valid_STP_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_STP_1))

result <- st_intersects(panel_sf, regions_valid_STP_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_STP_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="STP") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_STP_2.shp")

regions_valid_STP_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_STP_2))

result <- st_intersects(panel_sf, regions_valid_STP_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_STP_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="SWZ") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_SWZ_1.shp")

regions_valid_SWZ_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_SWZ_1))

result <- st_intersects(panel_sf, regions_valid_SWZ_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_SWZ_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="SWZ") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_SWZ_2.shp")

regions_valid_SWZ_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_SWZ_2))

result <- st_intersects(panel_sf, regions_valid_SWZ_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_SWZ_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="TUN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_TUN_1.shp")

regions_valid_TUN_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_TUN_1))

result <- st_intersects(panel_sf, regions_valid_TUN_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_TUN_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="TUN") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_TUN_2.shp")

regions_valid_TUN_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_TUN_2))

result <- st_intersects(panel_sf, regions_valid_TUN_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_TUN_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="ZMB") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_ZMB_1.shp")

regions_valid_ZMB_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_ZMB_1))

result <- st_intersects(panel_sf, regions_valid_ZMB_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_ZMB_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))



panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="ZMB") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_ZMB_2.shp")

regions_valid_ZMB_2 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_ZMB_2))

result <- st_intersects(panel_sf, regions_valid_ZMB_2)

result_with_region_2 <- st_join(panel_sf, regions_valid_ZMB_2, join = st_intersects)

result_with_region_2 <- as.data.frame(result_with_region_2)

result_with_region_2%<>%
  select(id_unique, NAME_2)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_2, by = "id_unique")%>%
    mutate(NAME_2= if_else(!is.na(NAME_2.x), NAME_2.x, NAME_2.y))%>%
    select(-c(NAME_2.x, NAME_2.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
afro_w8 %>%
  filter(is.na(NAME_2)) %>%
  group_by(ISO) %>%
  summarise(count_na = sum(is.na(NAME_2))) %>%
  View()

```

**Countries with 1 ADM level**

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="CPV") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_CPV_1.shp")

regions_valid_CPV_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_CPV_1))

result <- st_intersects(panel_sf, regions_valid_CPV_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_CPV_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="LSO") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_LSO_1.shp")

regions_valid_LSO_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_LSO_1))

result <- st_intersects(panel_sf, regions_valid_LSO_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_LSO_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
panel_sf <- afro_w8 %>%
  filter(!is.na(latitude) & !is.na(longitude)) %>%
  filter(ISO=="MUS") %>%
  select(id_unique, latitude, longitude, caplong, caplat)

regions <- st_read("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/Data/Data_Raw/gadm41_MUS_1.shp")

regions_valid_MUS_1 <- st_make_valid(regions)

panel_sf <- st_as_sf(panel_sf, coords = c("longitude", "latitude"), crs = st_crs(regions_valid_MUS_1))

result <- st_intersects(panel_sf, regions_valid_MUS_1)

result_with_region_1 <- st_join(panel_sf, regions_valid_MUS_1, join = st_intersects)

result_with_region_1 <- as.data.frame(result_with_region_1)

result_with_region_1%<>%
  select(id_unique, NAME_1)

afro_w8 <- as.data.frame(afro_w8)

afro_w8 %<>% left_join(result_with_region_1, by = "id_unique")%>%
    mutate(NAME_1= if_else(!is.na(NAME_1.x), NAME_1.x, NAME_1.y))%>%
    select(-c(NAME_1.x, NAME_1.y))

objects <- ls()
objects <- objects[objects != "afro_w8"]


```

```{r}
afro_w8 %>%
  group_by(ISO) %>%
  summarise(count_na = sum(is.na(NAME_1))) %>%
  print()
```

```{r}
saveRDS(afro_w8, file="Data/Data_RDS/afro_w8.rds")

```



