```{r}
setwd("~/Working paper/trust/script")
getwd()
```

```{r}
library(haven)
library(dplyr)
select <- dplyr::select
library(magrittr)
library(ncdf4)
library(sf)
library(raster)
library(exactextractr)
library(rgdal)
library(ggplot2)
```

```{r}
ncpath <- "data/data_raw/"
ncname <- "VHRFC"  
ncfname <- paste(ncpath, ncname, ".nc", sep="")
ncin <- nc_open(ncfname)
print(ncin)

FRD <- ncvar_get(ncin, "VHRFC_LIS_FRD")
dim(FRD)

lon <- ncvar_get(ncin, "Longitude")
lat <- ncvar_get(ncin, "Latitude")

r_FRD <- raster(t(FRD), 
                xmn=min(lon), xmx=max(lon), 
                ymn=min(lat), ymx=max(lat),
                crs=CRS("+proj=longlat +datum=WGS84"))

r_FRD <- flip(r_FRD, direction = "y")

nc_close(ncin)
```

```{r}
data_trust <- readRDS("Data/Data_RDS/final_df5.rds")
```

###ADM2
```{r}
countries_adm2 <- c("BEN", "BFA", "BWA", "CIV", "CMR", "GIN", "LBR", "MLI", "NAM", "NER", "SLE")

accumulated_results <- data.frame()


for (country in countries_adm2) {
shapefile_path <- paste0("C:/Users/Redha CHABA/Documents/Working paper/trust/script/data/data_Raw/gadm41_",country,"_0.shp")

country_shp <- readOGR(shapefile_path)

if (!identical(crs(r_FRD), crs(country_shp))) {
  country_shp <- spTransform(country_shp, crs(r_FRD))
}

cropped <- crop(r_FRD, extent(country_shp))
masked <- mask(cropped, country_shp)


data_file <- paste0("C:/Users/Redha CHABA/Documents/Working paper/trust/script/data/data_Raw/",country,"_pd_2011_1km_UNadj_ASCII_XYZ.csv")

pop <- raster(data_file)

print(pop)

pop_wgs84 <- projectRaster(pop, crs = CRS("+proj=longlat +datum=WGS84"))

pop_resampled <- resample(pop_wgs84, r_FRD, method="bilinear")

pop_wgs84_cropped <- crop(pop_resampled, extent(country_shp))
pop_wgs84_masked <- mask(pop_wgs84_cropped, country_shp)

plot(pop_wgs84_masked)

pop_resampled <- resample(pop_wgs84_masked, masked, method="bilinear")

if (!all(res(masked) == res(pop_wgs84_masked))) {
  pop_wgs84_resampled <- resample(pop_wgs84_masked, masked, method = "bilinear")
} else {
  pop_wgs84_resampled <- pop_wgs84_masked
}

if (!compareRaster(masked, pop_wgs84_resampled)) {
  stop("Les rasters n'ont pas la même résolution et/ou la même étendue après ajustement.")
}

Lightning_risk <- masked / (1 + pop_resampled)


shapefile <- paste0("C:/Users/Redha CHABA/Documents/Working paper/trust/script/data/data_Raw/gadm41_", country,"_2.shp")
  regions <- st_read(shapefile)
  regions <- st_make_valid(regions)

mean_flash <- exact_extract(masked, regions, 'mean')

regions$mean_flash <- mean_flash


regions %<>%
  as.data.frame()

regions %<>%
  rename(ISO=GID_0)%>%
  select(ISO, NAME_2, mean_flash)


accumulated_results <- rbind(accumulated_results, regions)
}

rounds <- data.frame(round = rep(5:8, each = nrow(accumulated_results)))

expanded_data <- accumulated_results[rep(1:nrow(accumulated_results), times = 4), ]

expanded_data$round <- rounds$round

expanded_data <- expanded_data %>% distinct(ISO, NAME_2, round, .keep_all = TRUE)


data_trust %<>% left_join(expanded_data, by=c("ISO", "NAME_2", "round"))

data_trust%<>%
  distinct(id_unique, .keep_all = TRUE)

glimpse(data_trust)

data_trust%>%
  select(mean_flash)%>%
  summary()
```
###ADM1
```{r}
countries_adm1 <- c("GHA","KEN","MOZ", "MWI","NGA","TZA","UGA","ZMB", "ZWE")

accumulated_results <- data.frame()


for (country in countries_adm1) {
shapefile_path <- paste0("C:/Users/Redha CHABA/Documents/Working paper/trust/script/data/data_Raw/gadm41_",country,"_0.shp")

country_shp <- readOGR(shapefile_path)

if (!identical(crs(r_FRD), crs(country_shp))) {
  country_shp <- spTransform(country_shp, crs(r_FRD))
}

cropped <- crop(r_FRD, extent(country_shp))
masked <- mask(cropped, country_shp)


data_file <- paste0("C:/Users/Redha CHABA/Documents/Working paper/trust/script/data/data_Raw/",country,"_pd_2011_1km_UNadj_ASCII_XYZ.csv")

pop <- raster(data_file)

print(pop)

pop_wgs84 <- projectRaster(pop, crs = CRS("+proj=longlat +datum=WGS84"))

pop_resampled <- resample(pop_wgs84, r_FRD, method="bilinear")

pop_wgs84_cropped <- crop(pop_resampled, extent(country_shp))
pop_wgs84_masked <- mask(pop_wgs84_cropped, country_shp)

plot(pop_wgs84_masked)

pop_resampled <- resample(pop_wgs84_masked, masked, method="bilinear")

if (!all(res(masked) == res(pop_wgs84_masked))) {
  pop_wgs84_resampled <- resample(pop_wgs84_masked, masked, method = "bilinear")
} else {
  pop_wgs84_resampled <- pop_wgs84_masked
}

if (!compareRaster(masked, pop_wgs84_resampled)) {
  stop("Les rasters n'ont pas la même résolution et/ou la même étendue après ajustement.")
}

Lightning_risk <- masked / (1 + pop_resampled)


shapefile <- paste0("C:/Users/Redha CHABA/Documents/Working paper/trust/script/data/data_Raw/gadm41_", country,"_1.shp")
  regions <- st_read(shapefile)
  regions <- st_make_valid(regions)

mean_flash <- exact_extract(masked, regions, 'mean')

regions$mean_flash <- mean_flash


regions %<>%
  as.data.frame()

regions %<>%
  rename(ISO=GID_0)%>%
  select(ISO, NAME_1, mean_flash)


accumulated_results <- rbind(accumulated_results, regions)
}

rounds <- data.frame(round = rep(5:8, each = nrow(accumulated_results)))

expanded_data <- accumulated_results[rep(1:nrow(accumulated_results), times = 4), ]

expanded_data$round <- rounds$round

expanded_data <- expanded_data %>% distinct(ISO, NAME_1, round, .keep_all = TRUE)


data_trust %<>% left_join(expanded_data, by=c("ISO", "NAME_1", "round"))

data_trust%<>%
  distinct(id_unique, .keep_all = TRUE)

glimpse(data_trust)


data_trust %<>%
  mutate(mean_flash = coalesce(mean_flash.x, mean_flash.y))%>%
  select(-c(mean_flash.x, mean_flash.y))

data_trust%<>%
  distinct(id_unique, .keep_all = TRUE)

data_trust%<>%
  mutate(tv=case_when(
    round==5 ~ 1,
    round==6 ~ 2,
    round==7 ~ 3,
    round==8 ~ 4,
  ))
glimpse(data_trust)
```


```{r}
saveRDS(data_trust, file="Data/Data_RDS/data_merge2.rds")
write_dta(data_trust, "Data/Data_dta/data_merge2.dta")
```



```{r}
shapefile_path <- "data/data_raw/gadm/gadm41_BEN_0.shp"

country <- readOGR(shapefile_path)


if (!identical(crs(r_FRD), crs(country))) {
  country <- spTransform(country, crs(r_FRD))
}

# Recadrer et masquer le raster gg_wgs84_recode selon les frontières du country
gg_wgs84_cropped <- crop(r_FRD, extent(country))
gg_wgs84_masked <- mask(gg_wgs84_cropped, country)

dev.off()

plot(gg_wgs84_masked)
```


```{r}
# Lecture du fichier de données
data_file <- paste0("data/data_raw/pop_density/BEN_PD_2011_1km_UNadj_ASCII_XYZ.csv")

pop <- raster(data_file)

print(pop)

pop_wgs84 <- projectRaster(pop, crs = CRS("+proj=longlat +datum=WGS84"))

print(pop_wgs84)

plot(pop_wgs84)

# Recadrer et masquer le raster pop_wgs84 selon les frontières du country
pop_wgs84_cropped <- crop(pop_wgs84, extent(country))
pop_wgs84_masked <- mask(pop_wgs84_cropped, country)

rm(data_file, pop, pop_wgs84, pop_wgs84_cropped)

# Vérifier si les résolutions sont les mêmes
if (!all(res(gg_wgs84_masked) == res(pop_wgs84_masked))) {
  # Ajuster la résolution de pop_wgs84_masked à celle de gg_wgs84_masked
  pop_wgs84_resampled <- resample(pop_wgs84_masked, gg_wgs84_masked, method = "bilinear")
} else {
  pop_wgs84_resampled <- pop_wgs84_masked
}

rm(pop_wgs84_masked)

# Vérifier de nouveau les étendues et les résolutions
if (!compareRaster(gg_wgs84_masked, pop_wgs84_resampled)) {
  stop("Les rasters n'ont pas la même résolution et/ou la même étendue après ajustement.")
}

# Multiplier les valeurs des deux rasters
gg_pop <- gg_wgs84_masked * pop_wgs84_resampled

# Afficher le raster résultant avec les contours du country
plot(gg_pop, main="Couverture Pondérée par Densité de Population")
plot(country, add=TRUE, border="darkgrey")

graphics.off()

plot(gg_wgs84_masked)
plot(pop_wgs84_resampled)
plot(gg_pop)


```


```{r}

regions <- st_read("data/data_raw/gadm/gadm41_BEN_2.shp")
regions <- st_make_valid(regions)

mean_gg <- exact_extract(gg_wgs84_masked, regions, 'mean')

regions$mean_gg <- mean_gg


ggplot() +
  geom_sf(data = regions, aes(fill = mean_gg), color = "white") +
  scale_fill_distiller(palette = "YlOrBr", direction = 1, name = "Internet Coverage")+
  theme_minimal() +
  theme(legend.position = "right", plot.title = element_text(hjust = 0.5, size = 16, face = "bold")) +
  labs(title = "Benin - Internet Coverage ADM2 - Round 8")


mean_pop <- exact_extract(pop_wgs84_resampled, regions, 'mean')

regions$mean_pop <- mean_pop

ggplot() +
  geom_sf(data = regions, aes(fill = mean_pop), color = "white") +
  scale_fill_distiller(palette = "YlOrBr", direction = 1, name = "Pop Density", breaks = c(min(regions$mean_pop), max(regions$mean_pop)), labels = c(0, 1)) +
  theme_minimal() +
  theme(legend.position = "right", plot.title = element_text(hjust = 0.5, size = 16, face = "bold")) +
  labs(title = "Benin - Population Density ADM2 - Round 7")


mean_gg_pop <- exact_extract(gg_pop, regions, 'mean')

regions$mean_gg_pop <- mean_gg_pop

ggplot() +
  geom_sf(data = regions, aes(fill = mean_gg_pop), color = "white") +
  scale_fill_distiller(palette = "YlOrBr", direction = 1, name = "Pop Density", breaks = c(min(regions$mean_gg_pop), max(regions$mean_gg_pop)), labels = c(0, 1)) +
  theme_minimal() +
  theme(legend.position = "right", plot.title = element_text(hjust = 0.5, size = 16, face = "bold")) +
  labs(title = "Benin - Weighted Population Density ADM2 - Round 7")


regions$pot_gg_pop <- mean_gg_pop/mean_pop

ggplot() +
  geom_sf(data = regions, aes(fill = pot_gg_pop), color = "white") +
  scale_fill_distiller(palette = "YlOrBr", direction = 1, name = "Pop Density", breaks = c(min(regions$pot_gg_pop), max(regions$pot_gg_pop)), labels = c(0, 1)) +
  theme_minimal() +
  theme(legend.position = "right", plot.title = element_text(hjust = 0.5, size = 16, face = "bold")) +
  labs(title = "Benin - Weighted Population Density ADM2 - Round 7")

```

```{r}
data_trust_test <- readRDS("C:/Users/Redha CHABA/Documents/Working paper/trust/script/data/data_RDS/final_df5.rds")

capitals <- data_final_nlp %>%
  select(caplong, caplat, iso) %>%
  na.omit() %>%
  rename(longitude = caplong, latitude = caplat)

capitals%<>%
  filter(iso=="BEN")%>%
  distinct(iso, .keep_all = TRUE)

ggplot() +
  geom_sf(data = regions, aes(fill = pot_gg_pop), color = "black") +
  scale_fill_distiller(palette = "RdPu", direction = 1, name = "Lightning strikes", breaks = c(min(regions$pot_gg_pop), max(regions$pot_gg_pop)), labels = NULL) +
  geom_point(data = capitals, 
             aes(x = longitude, y = latitude), 
             size = 4, shape = 22, fill = "green", show.legend = FALSE)+
  geom_text(aes(x = 2.5, y = 6.2, label = "Porto-Novo"), color = "black", size = 4, fontface="bold") +
    theme_minimal() +
  theme(
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),  
    panel.background = element_blank(),   
    axis.text = element_blank(),         
    axis.ticks = element_blank(),         
    axis.title = element_blank(),
    legend.position = c(1 ,0.35),
    plot.title = element_text(hjust = 0.5, size = 5, face = "bold")
  )

ggsave("plots/lightning_strikes/lightning_strikes.jpg", width = 8, height = 6, dpi = 300)

dev.off()
```
