```{r}
setwd("~/Working paper/Trust/Script")
getwd()
```

```{r}
library(haven)
library(dplyr)
select <- dplyr::select
library(magrittr)
library(ncdf4)
library(sf)
library(rgdal)
library(ggplot2)
```

```{r}
data_president <- read_xlsx("Data/Data_raw/data_president.xlsx")
data_president%<>%
  filter(!is.na(date_of_election))
```

```{r}
data_trust <- readRDS("Data/Data_RDS/final_df5.rds")
```

###ADM2
```{r}
countries_adm2 <- c("BEN", "BFA", "BWA", "CIV", "CMR", "GIN", "LBR", "MLI", "NAM", "NER", "SLE", "GHA","KEN","MOZ", "MWI","NGA","TZA","UGA","ZMB", "ZWE")
```

```{r}
# Charger les bibliothèques nécessaires
library(sf)
library(dplyr)

# Initialiser un DataFrame pour stocker les résultats
results <- data.frame()

# Boucle sur chaque combinaison unique de pays (ISO) et de période (round)
for (i in 1:nrow(unique_combinations)) {
  
  # Sélectionner le pays et le round actuels
  ISO <- unique_combinations$ISO[i]
  round <- unique_combinations$round[i]
  
  # Filtrer les données des présidents pour le pays et la période (round) actuels
  data_filtered <- data_president %>%
    filter(ISO == !!ISO, round == !!round)
  
  # Si le filtrage ne retourne aucune ligne, passer à la prochaine itération
  if (nrow(data_filtered) == 0) {
    warning(paste("Pas de données pour le pays", ISO, "et la période", round))
    next
  }
  
  # Générer le chemin du shapefile pour le pays actuel
  shapefile_path <- paste0("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/data/data_Raw/gadm41_", ISO, "_2.shp")
  
  # Vérifier si le fichier existe
  if (file.exists(shapefile_path)) {
    # Lire le shapefile et corriger les géométries si nécessaire
    regions_sf <- st_read(shapefile_path)
    regions_sf <- st_make_valid(regions_sf)
    
    # Convertir les lieux de naissance des présidents en objet spatial (sf)
    presidents_sf <- st_as_sf(data_filtered, coords = c("long_nais", "lat_nais"), crs = 4326)
    
    # Joindre les lieux de naissance aux régions pour identifier la région
    presidents_with_region <- st_join(presidents_sf, regions_sf, join = st_within)
    
    # Ajouter les colonnes pour le pays et le round dans les résultats
    presidents_with_region$ISO <- ISO
    presidents_with_region$round <- round
    
    # Ajouter les résultats pour cette combinaison au DataFrame final
    results <- rbind(results, presidents_with_region)
    
  } else {
    # Message d'avertissement si le shapefile du pays est manquant
    warning(paste("Shapefile pour le pays", ISO, "n'existe pas dans le chemin spécifié."))
  }
}

results%<>%
  select(ISO, round, NAME_1, NAME_2)

results%<>%
  select(-geometry)

results%<>%
  rename(NAME_2_pres=NAME_2,
         NAME_1_pres=NAME_1)

data_trust %<>% left_join(results, by=c("ISO", "round"))

data_trust %<>%
  mutate(pres_adm2=ifelse(NAME_2_pres==NAME_2, 1, 0))

data_trust %<>%
  mutate(pres_adm1=ifelse(NAME_1_pres==NAME_1, 1, 0))

saveRDS(data_trust, file="Data/Data_RDS/final_df5.rds")
write_dta(data_trust, "Data/Data_dta/final_df5.dta")

```

