```{r}
setwd("~/Working paper/Trust/Script")
getwd()
```

```{r}
library(raster)
library(dplyr)
library(magrittr)
library(sf)
library(exactextractr)
library(ggplot2)
library(haven)
library(terra)
library(rnaturalearth)
library(haven)

```

```{r}
final_df5 <- readRDS("Data/Data_RDS/final_df5.rds")

data_keep <- subset(final_df5, select = c("id_unique","latitude","longitude"))
data_keep_sf <- st_as_sf(data_keep, coords = c("longitude", "latitude"), crs = 4326)

remove(final_df5,data_keep)
```

```{r, adm0}
countries <- c("BEN", "BFA", "BWA", "CMR", "CIV", "GIN", "LBR", "MLI", "NAM", "NER", "SLE", "GHA", "KEN", "MOZ", "MWI", "NGA", "TZA", "UGA", "ZMB", "ZWE")

all_regions_0 <- list()

for (country in countries) {
  
  shapefile_0 <- paste0("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/data/data_Raw/gadm41_", country, "_0.shp")
  
  if (file.exists(shapefile_0)) {
    regions_0 <- st_read(shapefile_0, quiet = TRUE)
    regions_0 <- st_make_valid(regions_0)
    
    if (is.na(st_crs(regions_0))) {
      regions_0 <- st_set_crs(regions_0, 4326)
    }
    
    regions_0$country_code <- country
    regions_0$area_0_km2 <- as.numeric(st_area(regions_0)) / 10^6
    
    all_regions_0[[country]] <- regions_0
  } else {
    message("Fichier manquant pour ", country)
  }
}

df_regions_0 <- do.call(rbind, all_regions_0)
df_regions_0 <- st_make_valid(df_regions_0)

df_regions_0 <- st_transform(df_regions_0, crs = st_crs(data_keep_sf))

data_keep_sf_0 <- st_join(data_keep_sf, df_regions_0[, c("country_code", "area_0_km2")], join = st_intersects)

data_keep_sf_0%>%
  distinct(country_code, .keep_all = TRUE)%>%
  View()
```

```{r, adm1}
countries <- c("BEN", "BFA", "BWA", "CMR", "CIV", "GIN", "LBR", "MLI", "NAM", "NER", "SLE", "GHA", "KEN", "MOZ", "MWI", "NGA", "TZA", "UGA", "ZMB", "ZWE")

all_regions_1 <- list()

for (country in countries) {
  
  shapefile_1 <- paste0("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/data/data_Raw/gadm41_", country, "_1.shp")
  
  if (file.exists(shapefile_1)) {
    regions_1 <- st_read(shapefile_1, quiet = TRUE)
    regions_1 <- st_make_valid(regions_1)
    
    if (is.na(st_crs(regions_1))) {
      regions_1 <- st_set_crs(regions_1, 4326)
    }
    
    regions_1$country_code <- country
    regions_1$area_1_km2 <- as.numeric(st_area(regions_1)) / 10^6
    
    all_regions_1[[country]] <- regions_1
  } else {
    message("Fichier manquant pour ", country)
  }
}

df_regions_1 <- do.call(rbind, all_regions_1)
df_regions_1 <- st_make_valid(df_regions_1)

df_regions_1 <- st_transform(df_regions_1, crs = st_crs(data_keep_sf))

data_keep_sf_1 <- st_join(data_keep_sf_0, df_regions_1[, c("country_code", "area_1_km2")], join = st_intersects)

```


```{r}
countries <- c("BEN", "BFA", "BWA", "CMR", "CIV", "GIN", "LBR", "MLI", "NAM", "NER", "SLE", "GHA", "KEN", "MOZ", "MWI", "NGA", "TZA", "UGA", "ZMB", "ZWE")

all_regions_2 <- list()

for (country in countries) {
  
  shapefile_2 <- paste0("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/data/data_Raw/gadm41_", country, "_2.shp")
  
  if (file.exists(shapefile_2)) {
    regions_2 <- st_read(shapefile_2, quiet = TRUE)
    regions_2 <- st_make_valid(regions_2)
    
    if (is.na(st_crs(regions_2))) {
      regions_2 <- st_set_crs(regions_2, 4326)
    }
    
    regions_2$country_code <- country
    regions_2$area_2_km2 <- as.numeric(st_area(regions_2)) / 10^6
    
    all_regions_2[[country]] <- regions_2
  } else {
    message("Fichier manquant pour ", country)
  }
}

df_regions_2 <- do.call(rbind, all_regions_2)
df_regions_2 <- st_make_valid(df_regions_2)

df_regions_2 <- st_transform(df_regions_2, crs = st_crs(data_keep_sf))

data_keep_sf_2 <- st_join(data_keep_sf_1, df_regions_2[, c("country_code", "area_2_km2")], join = st_intersects)

data_superficie <- st_drop_geometry(data_keep_sf_2)
data_superficie <- subset(data_superficie, select=c("id_unique","country_code","area_0_km2","area_1_km2","area_2_km2"))


remove(all_regions_2, regions_2, country, df_regions_2, shapefile_2, countries, data_keep_sf_1, data_keep_sf_2)

saveRDS(data_superficie, file="Data/Data_RDS/data_area.rds")
write_dta(data_superficie, "Data/Data_dta/data_area.dta")

data_trust <- readRDS("Data/Data_RDS/final_df5.rds")

data_trust %<>% left_join(data_superficie, by="id_unique")
glimpse(data_trust)

saveRDS(data_trust, file="Data/Data_RDS/final_df6.rds")
write_dta(data_trust, "Data/Data_dta/final_df6.dta")

```





```{r, adm2}
Sys.setenv(SHAPE_RESTORE_SHX = "YES")
countries <- c("BEN", "BFA", "BWA", "CMR", "CIV", "GIN", "LBR", "MLI","NAM", "NER", "SLE", "GHA","KEN","MOZ","MWI","NGA","TZA","UGA","ZMB", "ZWE")

all_regions_2 <- list()

for (country in countries) {

  shapefile_2 <- paste0("C:/Users/Redha CHABA/Documents/Working paper/Trust/Script/data/data_Raw/gadm41_", country,"_2.shp")
  
  if (file.exists(shapefile_2)) {
    regions_2 <- st_read(shapefile_2, quiet = TRUE)
    regions_2 <- st_make_valid(regions_2)
    
    if (is.na(st_crs(regions_2))) {
      regions_2 <- st_set_crs(regions_2, 4326)  # Définir le CRS à EPSG:4326
    }
    
    regions_2 <- st_transform(regions_2, crs = 32630)
     
    regions_2$country_code <- country
    
    regions_2$area_2_km2 <- as.numeric(st_area(regions_2)) / 10^6

      all_regions_2[[country]] <- regions_2
  } else {
    message("Fichier manquant pour ", country)
  }
}

df_regions_2 <- do.call(rbind, all_regions_2)

df_regions_2 <- st_make_valid(df_regions_2)

df_regions_2 <- st_transform(df_regions_2, crs = st_crs(data_keep_sf_1))

data_keep_sf_2 <- st_join(data_keep_sf_1, df_regions_2[, c("country_code", "area_2_km2")], join = st_intersects)

data_superficie <- st_drop_geometry(data_keep_sf_2)
data_superficie <- subset(data_superficie, select=c("id_unique","country_code","area_0_km2","area_1_km2","area_2_km2"))


remove(all_regions_2, regions_2, country, df_regions_2, shapefile_2, countries, data_keep_sf_1, data_keep_sf_2)

saveRDS(data_superficie, file="Data/Data_RDS/data_area.rds")
write_dta(data_superficie, "Data/Data_dta/data_area.dta")

data_trust <- readRDS("Data/Data_RDS/final_df5.rds")

data_trust %<>% left_join(data_superficie, by="id_unique")

data_trust%<>%
  select(-country_code)

glimpse(data_trust)

data_trust%<>%
  mutate(area_region=case_when(
    ISO%in%c("BEN", "BFA", "BWA", "CIV", "CMR", "GIN", "LBR", "MLI", "NAM", "NER", "SLE")~area_2_km2,
    ISO%in%c("GHA","KEN","MOZ", "MWI","NGA","TZA","UGA","ZMB", "ZWE")~area_1_km2
  ))

data_trust%<>%
  mutate(area_region_log=log(1+area_region))

data_trust%>%
  select(area_region, area_region_log)%>%
  summary()

saveRDS(data_trust, file="Data/Data_RDS/final_df6.rds")
write_dta(data_trust, "Data/Data_dta/final_df6.dta")

data_trust%>%
distinct(ISO, .keep_all = TRUE)%>%
  select(ISO, area_0_km2)%>%
View()
```