

```{r}
load("C:/Users/Redha CHABA/Desktop/clea_lc_20240419.RData")

clea <- clea_lc_20240419

names(clea)

clea%<>%
  filter(rg=="Africa")


clea%>%
  distinct(ctr_n)%>%
  arrange(ctr_n)%>%
  View()

clea%>%
  distinct(ctr_n)%>%
  arrange(ctr_n)%>%
  filter(ctr_n%in%countries)%>%
  View()


clea%>%
  distinct(ctr_n, yr, cst_n, .keep_all = TRUE)%>%
  arrange(ctr_n, yr, cst_n )%>%
  filter(between(yr, 2011, 2018))%>%
  filter(ctr_n%in%countries)%>%
  filter(to1!=-990.0000000)%>%
  distinct(ctr_n, .keep_all = TRUE)%>%
  View()







clea%>%
  filter(ctr_n=="Nigeria")%>%
  distinct(yr)%>%
  View()


data_trust%>%
  distinct(ISO)%>%
print(n=25)

countries <- c("Benin", "Burkina Faso", "Botswana", "Cameroon", "Ivory Coast", 
               "Ghana", "Guinea", "Kenya", "Liberia", "Mali", 
               "Malawi", "Mozambique", "Namibia", "Niger", "Nigeria", 
               "Sierra Leone", "Tanzania", "Uganda", "Zambia", "Zimbabwe")

```

```{r}
afro_w7$DATEINTR <- trimws(afro_w7$DATEINTR)

afro_w7%>%select(DATEINTR)%>%count(DATEINTR)%>%print(n=2000)


afro_w6$dateintr <- trimws(afro_w6$dateintr)

afro_w6%>%select(dateintr)%>%arrange(dateintr)%>%count(dateintr)

afro_w5$dateintr <- trimws(afro_w5$dateintr)

afro_w5%>%select(dateintr)%>%arrange(dateintr)%>%count(dateintr)


```


```{r}

afro_w7%>%
  group_by(COUNTRY)%>%
  count(EANUMB_AB)%>%
  View()


afro_w7$COUNTRY

```

```{r}
afro_w8 <- read_sav("Data/Data_Raw/R8.Merge_34ctry_2nov21.release.w.local.info.sav")

data_trust <- readRDS("Data/Data_RDS/data_trust_report2.rds")
countries <- data_trust %>% distinct(ISO) %>% pull(ISO)

afro_w8%<>%
mutate(ISO = case_when(
    COUNTRY == 2  ~ "AGO",
    COUNTRY == 3  ~ "BEN",
    COUNTRY == 4  ~ "BWA",
    COUNTRY == 5  ~ "BFA",
    COUNTRY == 6  ~ "CPV",
    COUNTRY == 7  ~ "CMR",
    COUNTRY == 8  ~ "CIV",
    COUNTRY == 9  ~ "SWZ",
    COUNTRY == 10 ~ "ETH",
    COUNTRY == 11 ~ "GAB",
    COUNTRY == 12 ~ "GMB",
    COUNTRY == 13 ~ "GHA",
    COUNTRY == 14 ~ "GIN",
    COUNTRY == 15 ~ "KEN",
    COUNTRY == 16 ~ "LSO",
    COUNTRY == 17 ~ "LBR",
    COUNTRY == 19 ~ "MWI",
    COUNTRY == 20 ~ "MLI",
    COUNTRY == 21 ~ "MUS",
    COUNTRY == 22 ~ "MAR",
    COUNTRY == 23 ~ "MOZ",
    COUNTRY == 24 ~ "NAM",
    COUNTRY == 25 ~ "NER",
    COUNTRY == 26 ~ "NGA",
    COUNTRY == 28 ~ "SEN",
    COUNTRY == 29 ~ "SLE",
    COUNTRY == 30 ~ "ZAF",
    COUNTRY == 31 ~ "SDN",
    COUNTRY == 32 ~ "TZA",
    COUNTRY == 33 ~ "TGO",
    COUNTRY == 34 ~ "TUN",
    COUNTRY == 35 ~ "UGA",
    COUNTRY == 36 ~ "ZMB",
    COUNTRY == 37 ~ "ZWE",
    TRUE ~ NA_character_
  ))

afro_w8%<>%
  filter(ISO%in%countries)

afro_w8%<>%
  filter(!is.na(EA_GPS_LA))%>%
  filter(!is.na(LOCATION.LEVEL.2))%>%
  filter(!duplicated(RESPNO))

afro_w8%<>%
  mutate(round=rep(8, times = length("RESPNO")))%>%
  mutate(id=RESPNO)%>%
  mutate(id_unique=paste0(id,round))

afro_w8%<>%
rename(latitude=EA_GPS_LA,
       longitude=EA_GPS_LO,
       age=Q1,
       sex=Q101,
       rural=URBRUR,
       feelnat=Q82B,
       internet_use=Q92I,
       tele_pos=Q92B,
       internet_news=Q55D,
       tele_news=Q55B,
       radio_news=Q55A,
       journal_news=Q55C,
       sm_news=Q55E,
       prob=Q11B,
       commu=Q11A,
       corr_pres=Q42A,
       corr_dep=Q42B,
       corr_juge=Q42F,
       corr_local=Q42D,
       corr_level=Q43A,
       vote=Q13,
       trust_govpart=Q41E,
       trust_opppart=Q41F,
       perf_pres=Q51A,
       perf_mp=Q51B,
       perf_local=Q51C,
       perf_country=Q6A,
       trust_local=Q41D,
       trust_parl=Q41B,
       trust_pres=Q41A,
       trust_elec=Q41C,
       protest=Q11C,
       pref_demo=Q21,
       satis_demo=Q37,
       educ=Q97,
       emp=Q95A,
       disc_pol=Q9,
       extent=Q36,
       elec_fair=Q14,
       trust_trad=Q41K,
       corr_trad=Q42H,
       one_man=Q20C,
       one_party=Q20A,
       military=Q20B)
  
afro_w8%<>%
  select(ISO, round, id_unique,
         latitude, longitude, age, sex, rural, feelnat, internet_use, tele_pos, internet_news, tele_news,
         radio_news, journal_news, sm_news, prob, commu, corr_pres, corr_dep, corr_juge, corr_local, 
         corr_level, vote, trust_govpart, trust_opppart, perf_pres, perf_mp, perf_local, perf_country, 
         trust_local, trust_parl, trust_pres, trust_elec, protest, pref_demo, satis_demo, 
         educ, emp, disc_pol, extent, elec_fair, trust_trad, corr_trad, one_man, one_party, military)

country_var <- read_excel("Data/Data_Raw/country_var.xlsx")
gdppc <- read_excel("Data/Data_Raw/gdppc.xls")
population <- read_excel("Data/Data_Raw/pop.xls")
surface <- read_excel("Data/Data_Raw/surface.xls")
corr_index <- read_excel("Data/Data_Raw/corr_index.xlsx")

vdem <- readRDS("Data/Data_Raw/V-Dem-CY-Full+Others-v13.rds")
juriglobe <- read_excel("Data/Data_Raw/FR_index.xlsx")
cities <- read_excel("Data/Data_Raw/cities.xlsx")

country_var <-inner_join(country_var, corr_index, by ="ISO")%>%
  inner_join(gdppc, by="ISO")%>%
  inner_join(population, by="ISO")%>%
  inner_join(surface, by="ISO")

country_var%<>%
  select(ISO,cor2019_,gdpcap2019_, pop2019_, superficie2019_)

afro_w8 <- left_join(afro_w8, country_var, by = "ISO")

afro_w8%<>%
  rename(corr_index=cor2019_,
         gdppc=gdpcap2019_,
         area=superficie2019_,
         population=pop2019_)

afro_w8%<>%
  mutate(population=as.numeric(population) / 100000)%>%
  mutate(area=as.numeric(area) / 100)

afro_w8 <- left_join(afro_w8, cities, by = "ISO")

qog <- read.csv("Data/Data_raw/qog_std_ts_jan24.csv")

qog %<>%
  filter(year==2019)

countries <- unique(data_trust$ISO)

qog%<>%
  filter(ccodealp %in% countries)

qog%<>%
  select(year, ccodealp, aii_q55, aii_q56, vdem_mecorrpt, vdem_polyarchy)%>%
  rename(ISO=ccodealp, med_self_censor=aii_q55, citiz_self_censor=aii_q56, vdem_med_corrupt=vdem_mecorrpt)


qog%<>%
  rename(round=year)%>%
  mutate(round=8)


afro_w8 %<>% left_join(qog, by=c("ISO", "round"))




variables_to_process <- c("rural", "feelnat", "internet_use", "tele_pos", "internet_news", "tele_news",
         "radio_news", "journal_news", "sm_news", "prob", "commu", "corr_pres", "corr_dep", "corr_juge", "corr_local", 
         "corr_level", "vote", "trust_govpart", "trust_opppart", "perf_pres", "perf_mp", "perf_local", "perf_country", 
         "trust_local", "trust_parl", "trust_pres", "trust_elec", "protest", "pref_demo", "satis_demo",
         "emp", "disc_pol", "extent", "elec_fair", "trust_trad", "corr_trad", "one_man", "one_party", "military")

afro_w8 %<>%
  mutate(across(all_of(variables_to_process), 
                ~na_if(.x, 9) %>% na_if(-1) %>% na_if(8) %>% na_if(998) %>% na_if(460) %>% na_if(99) %>% na_if(997)%>% na_if(98) %>% na_if(1340)%>% na_if(9997) %>% na_if(9999) %>% na_if(9995) %>% na_if(9998)))

afro_w8%<>%
  mutate(educ=na_if(educ, 99))%>%
  mutate(educ=na_if(educ, -1))%>%
  mutate(educ=na_if(educ, 98))%>%
  mutate(feelnat=na_if(feelnat,7))

afro_w8%<>%
    mutate(rural = ifelse(rural == 3, 1, rural))

table_ccode<- data_trust%>%
  select(ISO, ccode)%>%
  distinct(ccode, .keep_all = TRUE)

afro_w8<- left_join(afro_w8, table_ccode, by="ISO")

afro_w8%<>%
  mutate(country_round=paste0(round,ccode))

afro_w8 %<>%
   mutate(pref_demo_simple=ifelse(pref_demo==3, 1, 0))%>%
  mutate(pref_demo_strict=ifelse(pref_demo==3 & one_party==1|one_party==2 & military==1|military==2 & one_man==1|one_man==2, 1, 0))%>%
   mutate(pref_demo_strict2=ifelse(pref_demo==3 & one_party==1 & military==1 & one_man==1, 1, 0))


rm(surface, population, juriglobe, gdppc, corr_index, cities, table_ccode, country_var, qog)

afro_w8%>%
  select(age)%>%
  summary()

glimpse(afro_w8)
```


```{r}
data_trust <- readRDS("Data/Data_RDS/data_trust_report2.rds")
afro_w8 <- readRDS("Data/Data_RDS/afro_w8.rds")

is_convertible_to_numeric <- function(column) {
  suppressWarnings(!any(is.na(as.numeric(as.character(column)))))
}

for (col in intersect(names(data_trust), names(afro_w8))) {
  if (is_convertible_to_numeric(data_trust[[col]]) && is_convertible_to_numeric(afro_w8[[col]])) {
    data_trust[[col]] <- as.numeric(as.character(data_trust[[col]]))
    afro_w8[[col]] <- as.numeric(as.character(afro_w8[[col]]))
  } else {
    data_trust[[col]] <- as.character(data_trust[[col]])
    afro_w8[[col]] <- as.character(afro_w8[[col]])
  }
}

data_trust_test <- bind_rows(data_trust, afro_w8)

library(tidyr)         

data_trust_test %<>%
  group_by(ISO) %>%
  mutate(presidential = ifelse(is.na(presidential), NA, presidential)) %>%
  ungroup() %>%
  fill(presidential, .direction = "updown")

data_trust_test %<>%
  group_by(ISO) %>%
  mutate(parlementarian = ifelse(is.na(parlementarian), NA, parlementarian)) %>%
  ungroup() %>%
  fill(parlementarian, .direction = "updown")

data_trust_test %<>%
  group_by(ISO) %>%
  mutate(semi_presidential = ifelse(is.na(semi_presidential), NA, semi_presidential)) %>%
  ungroup() %>%
  fill(semi_presidential, .direction = "updown")

data_trust_test %<>%
  group_by(ISO) %>%
  mutate(monarchical = ifelse(is.na(monarchical), NA, monarchical)) %>%
  ungroup() %>%
  fill(monarchical, .direction = "updown")

data_trust_test %<>%
  group_by(ISO) %>%
  mutate(gov_type = ifelse(is.na(gov_type), NA, gov_type)) %>%
  ungroup() %>%
  fill(gov_type, .direction = "updown")

data_trust_test%>%
  select(presidential, semi_presidential, monarchical, parlementarian, gov_type)%>%
  summary()


country_var <- read_excel("Data/Data_Raw/country_var.xlsx")
gdppc <- read_excel("Data/Data_Raw/gdppc.xls")
population <- read_excel("Data/Data_Raw/pop.xls")
corr_index <- read_excel("Data/Data_Raw/corr_index.xlsx")
cities <- read_excel("Data/Data_Raw/cities.xlsx")

country_var <-inner_join(country_var, corr_index, by ="ISO")%>%
  inner_join(gdppc, by="ISO")%>%
  inner_join(population, by="ISO")

country_var%<>%
  select(ISO,cor2019_,gdpcap2019_, pop2019_,cor2016_,gdpcap2016_, pop2016_, cor2014_, gdpcap2014_, pop2014_, cor2011_,gdpcap2011_, pop2011_)

data_trust_test%<>%
  select(-c("gdppc", "population", "corr_index", "vdem_polyarchy", "vdem_med_corrupt", "med_self_censor", "citiz_self_censor", "cname", "capname", "caplong", "caplat", "ncapname", "ncaplong", "ncaplat","sndncapname", "sndncaplong", "sndncaplat"))

data_trust_test %<>% left_join(country_var, by=c("ISO"))

data_trust_test %<>%
mutate(gdppc = case_when(
    round == 5 ~ gdpcap2011_,
    round == 6 ~ gdpcap2014_,
    round == 7 ~ gdpcap2016_,
    round == 8 ~ gdpcap2019_,
    TRUE ~ NA
  ))

data_trust_test %<>%
mutate(population = case_when(
    round == 5 ~ pop2011_,
    round == 6 ~ pop2014_,
    round == 7 ~ pop2016_,
    round == 8 ~ pop2019_,
    TRUE ~ NA
  ))

data_trust_test %<>%
mutate(corr_index = case_when(
    round == 5 ~ cor2011_,
    round == 6 ~ cor2014_,
    round == 7 ~ cor2016_,
    round == 8 ~ cor2019_,
    TRUE ~ NA
  ))


data_trust_test%<>%
  mutate(gdppc=as.numeric(gdppc))%>%
  mutate(population=as.numeric(population))%>%
  mutate(corr_index=as.numeric(corr_index))

data_trust_test%>%
  select(gdppc, population, corr_index)%>%
  summary()

countries <- unique(data_trust_test$ISO)

qog <- read.csv("Data/Data_raw/qog_std_ts_jan24.csv")

qog %<>%
  filter(year==2011|year==2014|year==2016|year==2019)

qog%<>%
  filter(ccodealp %in% countries)

qog%<>%
  select(year, ccodealp, aii_q55, aii_q56, vdem_mecorrpt, vdem_polyarchy)%>%
  rename(ISO=ccodealp, med_self_censor=aii_q55, citiz_self_censor=aii_q56, vdem_med_corrupt=vdem_mecorrpt)


qog%<>%
  rename(round=year)%>%
  mutate(round=case_when(round==2011 ~ 5,
                   round==2014 ~ 6,
                   round==2016 ~ 7,
                   round==2019 ~ 8))


data_trust_test %<>% left_join(qog, by=c("ISO", "round"))

data_trust_test %<>% left_join(cities, by=c("ISO"))

glimpse(data_trust_test)

```

```{r}

data_trust_test%<>%
  filter(longitude > -75)

data_trust_test %<>%
  filter(!is.na(longitude) & !is.na(latitude) & !is.na(caplong) & !is.na(caplat)) %>% 
 mutate(distance_cap = distGeo(
    cbind(longitude, latitude),
    cbind(caplong, caplat)
  ) / 1000)



data_trust_test %<>%
  filter(!is.na(longitude) & !is.na(latitude) & !is.na(ncaplong) & !is.na(ncaplat)) %>% 
  mutate(distance_ncap = distGeo(
    cbind(longitude, latitude),
    cbind(ncaplong, ncaplat)
  ) / 1000)


data_trust_test %<>%
  filter(!is.na(caplong) & !is.na(caplat) &!is.na(ncaplong) & !is.na(ncaplat)) %>% 
   mutate(distance_cap_ncap = distGeo(
    cbind(caplong, caplat),
    cbind(ncaplong, ncaplat)
  ) / 1000)


data_trust_test %<>%
  filter(!is.na(longitude) & !is.na(latitude) & !is.na(sndncaplong) & !is.na(sndncaplat)) %>% 
  mutate(distance_sndncap = distGeo(
    cbind(longitude, latitude),
    cbind(sndncaplong, sndncaplat)
  ) / 1000)


data_trust_test %<>%
  filter(!is.na(caplong) & !is.na(caplat) &!is.na(sndncaplong) & !is.na(sndncaplat)) %>% 
   mutate(distance_cap_sndncap = distGeo(
    cbind(caplong, caplat),
    cbind(sndncaplong, sndncaplat)
  ) / 1000)


data_trust_test%<>%
  mutate(distance_cap_10=distance_cap/10)


data_trust_test%<>%
  mutate(distance_ncap_10=distance_ncap/10)

data_trust_test%<>%
  mutate(distance_sndncap_10=distance_sndncap/10)

#Log distance

data_trust_test %<>%
  filter(!is.na(distance_cap))%>%
  mutate(distance_cap_log=log(distance_cap+1))%>%
  ungroup()

data_trust_test %<>%
  filter(!is.na(distance_ncap))%>%
  group_by(cname)%>%
  mutate(distance_ncap_log=log(distance_ncap+1))%>%
  ungroup()


data_trust_test %<>%
  filter(!is.na(distance_sndncap))%>%
  group_by(cname)%>%
  mutate(distance_sndncap_log=log(distance_sndncap+1))%>%
  ungroup()

#Max distance normalization

data_trust_test %<>%
  filter(!is.na(distance_cap))%>%
  group_by(cname)%>%
  mutate(distance_cap_max=max(distance_cap))%>%
  ungroup()


data_trust_test %<>%
  filter(!is.na(distance_cap))%>%
  group_by(cname)%>%
  mutate(distance_cap_max95=quantile(distance_cap, probs = 0.95))%>%
  ungroup()


data_trust_test %<>%
  filter(!is.na(distance_ncap)) %>%
  group_by(cname)%>%
  mutate(distance_ncap_max=max(distance_ncap))%>%
  ungroup()


data_trust_test %<>%
  filter(!is.na(distance_ncap)) %>%
  group_by(cname)%>%
  mutate(distance_ncap_max95=quantile(distance_ncap, probs = 0.95))%>%
  ungroup()



data_trust_test %<>%
  filter(!is.na(distance_sndncap)) %>%
  group_by(cname)%>%
  mutate(distance_sndncap_max=max(distance_sndncap))%>%
  ungroup()


data_trust_test %<>%
  filter(!is.na(distance_sndncap)) %>%
  group_by(cname)%>%
  mutate(distance_sndncap_max95=quantile(distance_sndncap, probs = 0.95))%>%
  ungroup()



 
 
#Cap
 
data_trust_test %<>%
  filter(!is.na(distance_cap_max)) %>%
  group_by(cname)%>%
  mutate(distance_cap_max_norm = distance_cap/distance_cap_max)%>%
  ungroup()


data_trust_test %<>%
  filter(!is.na(distance_cap_max95)) %>%
  group_by(cname)%>%
  mutate(distance_cap_max_norm95 = if_else(distance_cap<=distance_cap_max95,distance_cap/ distance_cap_max95, NA_real_))%>%
  ungroup()


#Ncap

data_trust_test %<>%
  filter(!is.na(distance_ncap_max)) %>%
  group_by(cname)%>%
  mutate(distance_ncap_max_norm = distance_ncap/distance_ncap_max)%>%
  ungroup()


data_trust_test %<>%
  filter(!is.na(distance_ncap_max95)) %>%
  group_by(cname)%>%
  mutate(distance_ncap_max_norm95 = if_else(distance_ncap<=distance_ncap_max95,distance_ncap/ distance_ncap_max95, NA_real_))%>%
  ungroup()

#sndNcap
data_trust_test %<>%
  filter(!is.na(distance_sndncap_max)) %>%
  group_by(cname)%>%
  mutate(distance_sndncap_max_norm = distance_sndncap/distance_sndncap_max)%>%
  ungroup()


data_trust_test %<>%
  filter(!is.na(distance_sndncap_max95)) %>%
  group_by(cname)%>%
  mutate(distance_sndncap_max_norm95 = if_else(distance_sndncap<=distance_sndncap_max95,distance_sndncap/ distance_sndncap_max95, NA_real_))%>%
  ungroup()

#Mean distance normalization

data_trust_test %<>%
  filter(!is.na(distance_cap))%>%
  group_by(cname)%>%
  mutate(distance_cap_mean=mean(distance_cap))%>%
  ungroup()

data_trust_test %<>%
  filter(!is.na(distance_ncap)) %>%
  group_by(cname)%>%
  mutate(distance_ncap_mean=mean(distance_ncap))%>%
  ungroup()

data_trust_test %<>%
  filter(!is.na(distance_sndncap)) %>%
  group_by(cname)%>%
  mutate(distance_sndncap_mean=mean(distance_sndncap))%>%
  ungroup()

 
 
#Cap
 
data_trust_test %<>%
  filter(!is.na(distance_cap_mean)) %>%
  group_by(cname)%>%
  mutate(distance_cap_mean_norm = distance_cap/distance_cap_mean)%>%
  ungroup()


#Ncap

data_trust_test %<>%
  filter(!is.na(distance_ncap_mean)) %>%
  group_by(cname)%>%
  mutate(distance_ncap_mean_norm = distance_ncap/distance_ncap_mean)%>%
  ungroup()


#sndNcap
data_trust_test %<>%
  filter(!is.na(distance_sndncap_mean)) %>%
  group_by(cname)%>%
  mutate(distance_sndncap_mean_norm = distance_sndncap/distance_sndncap_mean)%>%
  ungroup()


##Distance quintiles by country

#Raw
data_trust_test%<>%
  filter(!is.na(distance_cap)) %>%
  group_by(cname) %>%
  mutate(dist_cap_quint = ntile(distance_cap, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_ncap)) %>%
  group_by(cname) %>%
  mutate(dist_ncap_quint = ntile(distance_ncap, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_sndncap)) %>%
  group_by(cname) %>%
  mutate(dist_sndncap_quint = ntile(distance_sndncap, 5))%>%
  ungroup()

#log

data_trust_test%<>%
  filter(!is.na(distance_cap_log)) %>%
  group_by(cname) %>%
  mutate(dist_cap_quint_log = ntile(distance_cap_log, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_ncap_log)) %>%
  group_by(cname) %>%
  mutate(dist_ncap_quint_log = ntile(distance_ncap_log, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_sndncap_log)) %>%
  group_by(cname) %>%
  mutate(dist_sndncap_quint_log = ntile(distance_sndncap_log, 5))%>%
  ungroup()

#norm max
data_trust_test%<>%
  filter(!is.na(distance_cap_max_norm)) %>%
  group_by(cname) %>%
  mutate(dist_cap_quint_max_norm = ntile(distance_cap_max_norm, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_ncap_max_norm)) %>%
  group_by(cname) %>%
  mutate(dist_ncap_quint_max_norm = ntile(distance_ncap_max_norm, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_sndncap_max_norm)) %>%
  group_by(cname) %>%
  mutate(dist_sndncap_quint_max_norm = ntile(distance_sndncap_max_norm, 5))%>%
  ungroup()

#norm mean
data_trust_test%<>%
  filter(!is.na(distance_cap_mean_norm)) %>%
  group_by(cname) %>%
  mutate(dist_cap_quint_mean_norm = ntile(distance_cap_mean_norm, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_ncap_mean_norm)) %>%
  group_by(cname) %>%
  mutate(dist_ncap_quint_mean_norm = ntile(distance_ncap_mean_norm, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_sndncap_mean_norm)) %>%
  group_by(cname) %>%
  mutate(dist_sndncap_quint_mean_norm = ntile(distance_sndncap_mean_norm, 5))%>%
  ungroup()


##Distance quintiles all sample

#Raw
data_trust_test%<>%
  filter(!is.na(distance_cap)) %>%
  mutate(dist_cap_quint_all = ntile(distance_cap, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_ncap)) %>%
  mutate(dist_ncap_quint_all = ntile(distance_ncap, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_sndncap)) %>%
  mutate(dist_sndncap_quint_all = ntile(distance_sndncap, 5))%>%
  ungroup()

#log

data_trust_test%<>%
  filter(!is.na(distance_cap_log)) %>%
  mutate(dist_cap_quint_log_all = ntile(distance_cap_log, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_ncap_log)) %>%
  mutate(dist_ncap_quint_log_all = ntile(distance_ncap_log, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_sndncap_log)) %>%
  mutate(dist_sndncap_quint_log_all = ntile(distance_sndncap_log, 5))%>%
  ungroup()

#norm max
data_trust_test%<>%
  filter(!is.na(distance_cap_max_norm)) %>%
  mutate(dist_cap_quint_max_norm_all = ntile(distance_cap_max_norm, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_ncap_max_norm)) %>%
  mutate(dist_ncap_quint_max_norm_all = ntile(distance_ncap_max_norm, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_sndncap_max_norm)) %>%
  mutate(dist_sndncap_quint_max_norm_all = ntile(distance_sndncap_max_norm, 5))%>%
  ungroup()

#norm mean
data_trust_test%<>%
  filter(!is.na(distance_cap_mean_norm)) %>%
  mutate(dist_cap_quint_mean_norm_all = ntile(distance_cap_mean_norm, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_ncap_mean_norm)) %>%
  mutate(dist_ncap_quint_mean_norm_all = ntile(distance_ncap_mean_norm, 5))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_sndncap_mean_norm)) %>%
  mutate(dist_sndncap_quint_mean_norm_all = ntile(distance_sndncap_mean_norm, 5))%>%
  ungroup()




#Distance deciles

data_trust_test%<>%
  filter(!is.na(distance_cap)) %>%
  group_by(cname) %>%
  mutate(distance_cap_dec = ntile(distance_cap, 10))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_cap_max)) %>%
  group_by(cname) %>%
  mutate(distance_cap_dec_max = ntile(distance_cap_max, 10))%>%
  ungroup()


data_trust_test%<>%
  filter(!is.na(distance_ncap)) %>%
  group_by(cname) %>%
  mutate(distance_ncap_dec = ntile(distance_ncap, 10))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_ncap)) %>%
  group_by(cname) %>%
  mutate(distance_ncap_dec_max = ntile(distance_ncap_max, 10))%>%
  ungroup()




data_trust_test%<>%
  filter(!is.na(distance_sndncap)) %>%
  group_by(cname) %>%
  mutate(distance_sndncap_dec = ntile(distance_sndncap, 10))%>%
  ungroup()

data_trust_test%<>%
  filter(!is.na(distance_sndncap)) %>%
  group_by(cname) %>%
  mutate(distance_sndncap_dec_max = ntile(distance_sndncap_max, 10))%>%
  ungroup()

data_trust%>%
  select(distance_cap_max_norm, distance_sndncap_max_norm, distance_cap)%>%
  summary()

data_trust_test%>%
  select(distance_cap_max_norm, distance_sndncap_max_norm, distance_cap)%>%
  summary()

glimpse(data_trust_test)
```

```{r}
data_trust_test <- readRDS("Data/Data_RDS/data_trust_test_report2.rds")

data_trust_test %<>%
  mutate(trust_pres = as.numeric(trust_pres),
    trust_parl = as.numeric(trust_parl),
    trust_elec = as.numeric(trust_elec)
  )

data_trust_test %<>%
group_by(id_unique) %>%
mutate(mean_inst_trust = ifelse(all(!is.na(c(trust_pres, trust_parl, trust_elec))), 
                                      mean(c(trust_pres, trust_parl, trust_elec), na.rm = TRUE), 
                                      NA)) %>%
  ungroup()

data_trust_test%>%
  filter(is.na(bin_conditions_eco))%>%
  View()


afro_w8 <- read_sav("Data/Data_Raw/R8.Merge_34ctry_2nov21.release.w.local.info.sav")

afro_w8%<>%
  filter(!is.na(EA_GPS_LA))%>%
  filter(!is.na(LOCATION.LEVEL.2))%>%
  filter(!duplicated(RESPNO))

afro_w8%<>%
  select(RESPNO, Q4B)%>%
  rename(id=RESPNO)

afro_w8%<>%
  mutate(round=8)%>%
  mutate(id_unique=paste0(id,round))%>%
  select(id_unique, Q4B)%>%
  rename(conditions_eco=Q4B)

afro_w8%<>%
  mutate(bin_conditions_eco=ifelse(conditions_eco>=3, 1, 0))

afro_w8%<>%
  select(id_unique, bin_conditions_eco)

data_trust_test <- left_join(data_trust_test, afro_w8, by="id_unique")

glimpse(data_trust_test)


data_trust_test%>%
  select(bin_conditions_eco, ISO, round)%>%
  filter(is.na(bin_conditions_eco))%>%
  View()


data_trust_test%<>%
  mutate(bin_conditions_eco = case_when(
    round == 8 ~ bin_conditions_eco.y,
    round %in% c(5,6,7) ~ bin_conditions_eco.x))

data_trust_test%<>%
  select(-c(bin_conditions_eco.y, bin_conditions_eco.x))


str(data_trust_test)

data_trust_test %<>%
  mutate(age=as.numeric(age))%>%
  mutate(age_2 = age^2)

data_trust_test%<>%
    mutate(educ=as.numeric(educ))%>%
    mutate(educ_sec=case_when(
    educ %in% c(5, 6,7,8,9) ~ 1,
    educ %in% c(0,1,2, 3, 4) ~0,
    TRUE ~ NA_real_     
  ))


data_trust_test %<>%
  group_by(NAME_2) %>%
  mutate(region2_id = cur_group_id())%>%
  ungroup()

data_trust_test %<>%
  group_by(round, region2_id) %>%
  mutate(region2_round = cur_group_id())%>%
  ungroup()

data_trust_test%<>%
  mutate(area_log = if_else(!is.na(area), log(area), NA_real_))

data_trust_test%<>%
  mutate(log_gdppc=log(gdppc))

data_trust_test %<>%
  group_by(ISO) %>%
  mutate(color = ifelse(is.na(color), NA, color)) %>%
  ungroup() %>%
  fill(color, .direction = "updown")


data_trust_test %<>%
  mutate(mean_inst_trust_bin = case_when(
    mean_inst_trust >= median(mean_inst_trust, na.rm = TRUE) ~ 1,
    mean_inst_trust < median(mean_inst_trust, na.rm = TRUE) ~ 0,
    TRUE ~ NA_real_
  )) %>%
  ungroup()

data_trust_test%<>%
  mutate(internet_news_bin=case_when(
    internet_news%in%c(0,1, 2) ~ 0,
    internet_news%in%c(3, 4) ~ 1,
    TRUE ~ NA_real_
  ))

data_trust_test%<>%
  mutate(internet_news_bin2=case_when(
    internet_news%in%c(0,1, 2) ~ 0,
    internet_news%in%c(3, 4) ~ 1,
    TRUE ~ NA_real_
  ))

saveRDS(data_trust_test, file="Data/Data_RDS/data_trust_test_report2.rds")

write_dta(data_trust_test, "Data/Data_dta/data_trust_test_report2.dta")
```



